/* ============================================================
   PRELIM EXAM MODULE — file upload/extraction (DOCX/PDF),
   AI generation, preview, DOCX export.
   Also contains shared reference-file helpers (feWordXmlToText,
   feHandleFiles, feRenderRefList, feRemoveRef, feBuildRefContext)
   exactly as originally placed.
   ============================================================ */
function prelimHandleDrop(e){
  e.preventDefault();
  document.getElementById('prelimDropZone').style.background='#F9FBE7';
  prelimHandleFiles(e.dataTransfer.files);
}

async function prelimHandleFiles(fileList){
  const files = Array.from(fileList).filter(f => /\.(docx|doc|pdf)$/i.test(f.name));
  if(!files.length){ toast('Please upload .docx, .doc, or .pdf files only.','te'); return; }
  if(files.length + prelimFiles.length > 6){
    toast('Maximum 6 files allowed. Remove some first.','te'); return;
  }
  for(const file of files){
    const text = await prelimExtractDocx(file);
    prelimFiles.push({ name: file.name, text });
  }
  prelimRenderFileList();
}

async function prelimExtractDocx(file){
  const name = file.name.toLowerCase();
  if(name.endsWith('.pdf')){
    return await prelimExtractPDF(file);
  } else {
    // .docx and .doc both use ZIP+XML (modern .doc saved as docx also works; legacy binary .doc falls back gracefully)
    return await prelimExtractDOCX(file);
  }
}

/* Convert a chunk of Word XML (WordML) into clean plain text — every tag
   becomes a line break, so paragraphs/table cells/runs stay separated. */
function feWordXmlToText(xmlText){
  return xmlText
    .replace(/<[^>]+>/g, '\n')
    .replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>')
    .replace(/&apos;/g,"'").replace(/&quot;/g,'"')
    .split('\n').map(s=>s.trim()).filter(Boolean).join('\n');
}

async function prelimExtractDOCX(file){
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = async (e) => {
      try {
        const buf = e.target.result;
        const head = new Uint8Array(buf.slice(0,4));
        const isZip = head[0]===0x50 && head[1]===0x4B; // 'PK' — real .docx (ZIP)

        if(isZip){
          if(typeof JSZip === 'undefined'){
            await new Promise((res, rej) => {
              const s = document.createElement('script');
              s.src = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js';
              s.onload = res; s.onerror = rej;
              document.head.appendChild(s);
            });
          }
          const zip = await JSZip.loadAsync(buf);
          const xmlFile = zip.file('word/document.xml');
          if(!xmlFile){
            resolve('(Legacy .doc format — content may be limited: ' + file.name + ')');
            return;
          }
          const xmlText = await xmlFile.async('text');
          resolve(feWordXmlToText(xmlText));
          return;
        }

        // Not a ZIP — try decoding as WordML 2003 XML (Word-saved-as-XML .doc,
        // e.g. files generated by the Pointers/Lesson Plan tools: starts with
        // <?xml ...?> and/or <?mso-application progid="Word.Document"?>)
        const text = new TextDecoder('utf-8').decode(buf);
        if(/<\?mso-application|<w:wordDocument|<w:t[ >]/i.test(text)){
          resolve(feWordXmlToText(text));
          return;
        }

        resolve('(Legacy binary .doc format not supported — please save/export as .docx or .pdf: ' + file.name + ')');
      } catch(err){
        resolve('(Could not read ' + file.name + ': ' + err.message + ')');
      }
    };
    reader.readAsArrayBuffer(file);
  });
}

async function prelimExtractPDF(file){
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = async (e) => {
      try {
        // Load PDF.js from CDN if not present
        if(typeof pdfjsLib === 'undefined'){
          await new Promise((res, rej) => {
            const s = document.createElement('script');
            s.src = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';
            s.onload = () => {
              pdfjsLib.GlobalWorkerOptions.workerSrc =
                'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
              res();
            };
            s.onerror = rej;
            document.head.appendChild(s);
          });
        }
        const typedArray = new Uint8Array(e.target.result);
        const pdf = await pdfjsLib.getDocument({ data: typedArray }).promise;
        let fullText = '';
        for(let i = 1; i <= pdf.numPages; i++){
          const page = await pdf.getPage(i);
          const tc = await page.getTextContent();
          const pageText = tc.items.map(item => item.str).join(' ');
          fullText += pageText + '\n';
        }
        resolve(fullText.replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim());
      } catch(err){
        resolve('(Could not read PDF ' + file.name + ': ' + err.message + ')');
      }
    };
    reader.readAsArrayBuffer(file);
  });
}

function prelimRenderFileList(){
  const list = document.getElementById('prelimFileList');
  const items = document.getElementById('prelimFileItems');
  if(!prelimFiles.length){ list.style.display='none'; return; }
  list.style.display='block';
  items.innerHTML = prelimFiles.map((f,i) => `
    <div style="display:flex;align-items:center;gap:8px;background:#F1F8E9;border-radius:6px;padding:7px 10px;">
      <span style="font-size:14px;">📄</span>
      <span style="flex:1;font-size:12px;font-weight:600;color:#33691E;">${esc(f.name)}</span>
      <span style="font-size:10px;color:#888;">${f.text.length} chars</span>
      <button onclick="prelimRemoveFile(${i})" style="background:none;border:none;cursor:pointer;color:#C62828;font-size:14px;padding:0 4px;" title="Remove">✕</button>
    </div>`).join('');
}

function prelimRemoveFile(i){
  prelimFiles.splice(i,1);
  prelimRenderFileList();
}

/* ── Final Exam reference files (read by AI; item count/order still from TOS) ── */
let feRefFiles = [];   // [{name, text}]
async function feHandleFiles(fileList){
  const files = Array.from(fileList).filter(f => /\.(docx|doc|pdf)$/i.test(f.name));
  if(!files.length){ toast('Please upload .docx, .doc, or .pdf files only.','te'); return; }
  if(files.length + feRefFiles.length > 6){ toast('Maximum 6 reference files.','te'); return; }
  for(const file of files){
    const text = await prelimExtractDocx(file);   // reuse existing docx/pdf extractor
    feRefFiles.push({ name:file.name, text });
  }
  document.getElementById('feRefInput').value='';
  feRenderRefList();
}
function feRenderRefList(){
  const list = document.getElementById('feRefList');
  if(!list) return;
  list.innerHTML = feRefFiles.map((f,i)=>`
    <div style="display:flex;align-items:center;gap:8px;background:#F1F8E9;border-radius:6px;padding:7px 10px;">
      <span style="font-size:14px;">📄</span>
      <span style="flex:1;font-size:12px;font-weight:600;color:#33691E;">${esc(f.name)}</span>
      <span style="font-size:10px;color:#888;">${f.text.length} chars</span>
      <button onclick="feRemoveRef(${i})" style="background:none;border:none;cursor:pointer;color:#C62828;font-size:14px;padding:0 4px;" title="Remove">✕</button>
    </div>`).join('');
}
function feRemoveRef(i){ feRefFiles.splice(i,1); feRenderRefList(); }
function feBuildRefContext(){
  if(!feRefFiles.length) return '';
  const combined = feRefFiles.map((f,i)=>`--- FILE ${i+1}: ${f.name} ---\n${f.text}`).join('\n\n').slice(0, 12000);
  return combined;
}

/* ── Main generation ── */
async function prelimGenerate(){
  const apiKey = getActiveKey();
  if(!apiKey){ toast('⚠️ No API key. Add one in the API Key Manager.','te'); return; }
  if(prelimFiles.length < 3){ toast('Please upload at least 3 reference files (.docx, .doc, or .pdf).','te'); return; }

  const subject = document.getElementById('prelimSubject').value.trim() || 'the subject';
  const grade   = document.getElementById('prelimGrade').value;
  const quarter = document.getElementById('prelimQuarter').value;
  const tfCount = parseInt(document.getElementById('prelimTF').value) || 20;
  const wbCount = parseInt(document.getElementById('prelimWB').value) || 10;
  const essayCount = parseInt(document.getElementById('prelimEssay').value) || 2;

  const isFil = /\bfilipino\b/i.test(subject) || /\barpan\b/i.test(subject);

  // Build combined context from uploaded files
  const combinedContext = prelimFiles.map((f,i) =>
    `=== FILE ${i+1}: ${f.name} ===\n${f.text.slice(0,3000)}`
  ).join('\n\n');

  const genBtn = document.getElementById('prelimGenBtn');
  const gp = document.getElementById('prelimGP');
  const gfill = document.getElementById('prelimGFill');
  const gstat = document.getElementById('prelimGStat');
  const dlBtn = document.getElementById('prelimDlBtn');

  genBtn.disabled = true;
  genBtn.textContent = '⏳ Generating…';
  gp.style.display = 'block';
  gfill.style.width = '10%';
  dlBtn.style.display = 'none';
  document.getElementById('prelimPreview').style.display = 'none';
  prelimResult = null;

  const lang = isFil ? 'FILIPINO (Tagalog)' : 'ENGLISH';
  const langNote = isFil
    ? 'MAHALAGA: Isulat ang LAHAT ng tanong, salita, at sagot SA FILIPINO/TAGALOG. Angkop sa antas ng Grades 4-6.'
    : 'Write all questions and content in ENGLISH appropriate for Grades 4-6.';

  gstat.textContent = 'Generating Part I — True or False…';
  gfill.style.width = '20%';

  // PART I — True or False
  const prompt1 = isFil ? `
Ikaw ay isang guro na gumagawa ng Prelim Exam para sa ${grade} ${subject} (${quarter} Quarter).
Batay sa mga sumusunod na sangguniang dokumento, gumawa ng eksaktong ${tfCount} True or False na tanong.

KONTEKSTO MULA SA MGA DOKUMENTO:
${combinedContext}

${langNote}

Mga Panuntunan:
- Gumawa ng eksaktong ${tfCount} tanong na True o False
- Ibatay ang lahat ng tanong sa nilalaman ng mga dokumento
- Isama ang pangalan ng kwento/paksa bilang "story" field (halimbawa: "Ang Bahay sa Bato")
- Ang mga tanong ay dapat angkop sa ${grade} na mag-aaral
- Sagutin LAMANG ng valid JSON. Walang markdown, walang backticks.

{
  "story": "Pangalan ng Kwento o Paksa",
  "items": [
    {"q": "Ang tanong dito.", "answer": true},
    {"q": "Isa pang tanong.", "answer": false}
  ]
}` : `
You are a teacher creating a Prelim Exam for ${grade} ${subject} (${quarter} Quarter).
Based on the reference documents below, create exactly ${tfCount} True or False questions.

CONTEXT FROM UPLOADED DOCUMENTS:
${combinedContext}

${langNote}

Rules:
- Create exactly ${tfCount} True/False questions
- Base all questions on content from the documents
- Include the story/topic name as the "story" field
- Questions must be appropriate for ${grade} students
- Respond ONLY with valid JSON. No markdown, no backticks.

{
  "story": "Story or Topic Name",
  "items": [
    {"q": "The question here.", "answer": true},
    {"q": "Another question.", "answer": false}
  ]
}`;

  let part1, part2, part3;

  try {
    gstat.textContent = 'Generating Part I — True or False…';
    gfill.style.width = '25%';
    part1 = await prelimGenerateOnePart(prompt1, 'Part I');

    gstat.textContent = 'Generating Part II — Word Bank…';
    gfill.style.width = '55%';

    const prompt2 = isFil ? `
Batay sa mga sangguniang dokumento, gumawa ng Word Bank (Fill in the Blanks) na may eksaktong ${wbCount} tanong para sa ${grade} ${subject}.

KONTEKSTO:
${combinedContext}

${langNote}

- Gumawa ng ${wbCount} fill-in-the-blank na pangungusap
- Isama ang lahat ng sagot sa isang "wordBank" array (10 salita, maaaring may dagdag na 2-3 na panlito)
- Isama ang pangalan ng kwento/paksa bilang "story" field
- Sagutin LAMANG ng valid JSON.

{
  "story": "Pangalan ng Kwento",
  "wordBank": ["salita1","salita2","salita3"],
  "items": [
    {"q": "Si __________ ay pumunta sa bundok.", "answer": "Juan"}
  ]
}` : `
Based on the reference documents, create a Word Bank exercise with exactly ${wbCount} fill-in-the-blank sentences for ${grade} ${subject}.

CONTEXT:
${combinedContext}

${langNote}

- Create ${wbCount} fill-in-the-blank sentences
- Include all answers in a "wordBank" array (add 2-3 extra distractor words)
- Include the story/topic name as "story" field
- Respond ONLY with valid JSON.

{
  "story": "Story Name",
  "wordBank": ["word1","word2","word3"],
  "items": [
    {"q": "The __________ went to the mountain.", "answer": "man"}
  ]
}`;

    const raw2 = await prelimGenerateOnePart(prompt2, 'Part II');
    part2 = raw2;

    gstat.textContent = 'Generating Part III — Essay…';
    gfill.style.width = '80%';

    const prompt3 = isFil ? `
Batay sa mga sangguniang dokumento, gumawa ng eksaktong ${essayCount} essay na tanong para sa ${grade} ${subject}.

KONTEKSTO:
${combinedContext}

${langNote}

- Ang bawat tanong ay dapat sumagot ng 1-2 pangungusap
- Isama ang pangalan ng kwento/paksa bilang "story" field
- Sagutin LAMANG ng valid JSON.

{
  "story": "Pangalan ng Kwento",
  "items": [
    {"q": "Bakit mahalaga ang... ?"}
  ]
}` : `
Based on the reference documents, create exactly ${essayCount} essay questions for ${grade} ${subject}.

CONTEXT:
${combinedContext}

${langNote}

- Each question should be answered in 1-2 sentences
- Include the story/topic name as "story" field
- Respond ONLY with valid JSON.

{
  "story": "Story Name",
  "items": [
    {"q": "Why is it important that... ?"}
  ]
}`;

    const raw3 = await prelimGenerateOnePart(prompt3, 'Part III');
    part3 = raw3;

    gfill.style.width = '100%';
    gstat.textContent = '✅ Done!';

    prelimResult = { part1, part2, part3, subject, grade, quarter, isFil, tfCount, wbCount, essayCount };
    prelimRenderPreview();
    dlBtn.style.display = '';
    toast('✅ Prelim Exam generated successfully!','ts');
  } catch(e){
    console.error(e);
    if(e.message === 'QUOTA'){
      toast('🚫 All API keys hit their quota. Add a new key, or wait a bit and reset quotas in the API Key Manager, then try again.','te');
      gstat.textContent = '🚫 All keys hit quota — add/reset a key and try again.';
    } else if(e.message === 'NO_KEY'){
      toast('⚠️ No usable API key left. Add or reset one in the API Key Manager.','te');
      gstat.textContent = '⚠️ No usable API key.';
    } else {
      toast('❌ Error generating prelim exam: ' + e.message,'te');
      gstat.textContent = '❌ Error: ' + e.message;
    }
  }

  genBtn.disabled = false;
  genBtn.textContent = '🤖 Generate Prelim Exam';
}

/* ── AI call for prelim (uses active provider) ──
   Detects REAL quota/rate-limit signals (HTTP 429 or documented quota codes)
   and throws Error('QUOTA') so the caller can rotate to the next key —
   matching how the Final Exam and Lesson Plan generators already behave.
   Any other failure throws a normal Error with the provider's message. ── */
function prelimIsRealQuota(status, errBody){
  if(status === 429) return true;
  const code = String(errBody?.error?.code || errBody?.error?.type || '').toLowerCase();
  const msg  = String(errBody?.error?.message || errBody?.message || '').toLowerCase();
  return (
    code.includes('rate_limit_exceeded') ||
    code.includes('insufficient_quota') ||
    code.includes('quota_exceeded') ||
    msg.includes('rate limit exceeded') ||
    msg.includes('insufficient_quota') ||
    msg.includes('you exceeded your current quota') ||
    msg.includes('requests per minute') ||
    msg.includes('requests per day') ||
    msg.includes('tokens per minute') ||
    msg.includes('too many requests')
  );
}
async function prelimCallAI(prompt, apiKey){
  const keyObj = mkKeys[mkActive] || {};
  const provider = feDetectProvider(apiKey, keyObj.provider);
  const SYS = 'Return only valid JSON. No markdown. No backticks. No explanation.';

  if(provider === 'openai' || provider === 'groq'){
    const url = provider==='groq'
      ? 'https://api.groq.com/openai/v1/chat/completions'
      : 'https://api.openai.com/v1/chat/completions';
    const model = provider==='groq' ? 'llama-3.3-70b-versatile' : 'gpt-4o-mini';
    const r = await fetch(url,{ method:'POST', headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey},
      body:JSON.stringify({ model, max_tokens:4096, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); if(prelimIsRealQuota(r.status,e)) throw new Error('QUOTA'); throw new Error(e.error?.message||'HTTP '+r.status); }
    const d=await r.json(); return d.choices?.[0]?.message?.content||'';

  } else if(provider === 'mistral'){
    const r = await fetch('https://api.mistral.ai/v1/chat/completions',{ method:'POST',
      headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey},
      body:JSON.stringify({ model:'mistral-small-latest', max_tokens:4096, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); if(prelimIsRealQuota(r.status,e)) throw new Error('QUOTA'); throw new Error(e.message||e.error?.message||'HTTP '+r.status); }
    const d=await r.json(); return d.choices?.[0]?.message?.content||'';

  } else if(provider === 'deepseek'){
    const r = await fetch('https://api.deepseek.com/v1/chat/completions',{ method:'POST',
      headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey},
      body:JSON.stringify({ model:'deepseek-chat', max_tokens:4096, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); if(prelimIsRealQuota(r.status,e)) throw new Error('QUOTA'); throw new Error(e.error?.message||'HTTP '+r.status); }
    const d=await r.json(); return d.choices?.[0]?.message?.content||'';

  } else if(provider === 'cohere'){
    const r = await fetch('https://api.cohere.com/v2/chat',{ method:'POST',
      headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey},
      body:JSON.stringify({ model:'command-r-plus', max_tokens:4096, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); if(prelimIsRealQuota(r.status,e)) throw new Error('QUOTA'); throw new Error(e.message||'HTTP '+r.status); }
    const d=await r.json(); return d.message?.content?.[0]?.text||'';

  } else if(provider === 'openrouter'){
    const r = await fetch('https://openrouter.ai/api/v1/chat/completions',{ method:'POST',
      headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey,
        'HTTP-Referer':'https://localhost','X-Title':'Prelim Exam Generator'},
      body:JSON.stringify({ model:'openrouter/free', max_tokens:2048, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){
      const e=await r.json().catch(()=>({}));
      const raw = e.error?.metadata?.raw;
      const inner = raw ? (() => { try { return JSON.parse(raw); } catch(_){ return null; } })() : null;
      if(prelimIsRealQuota(r.status, inner||e)) throw new Error('QUOTA');
      throw new Error(inner?.error?.message || e.error?.message || 'HTTP '+r.status);
    }
    const d=await r.json(); return d.choices?.[0]?.message?.content||'';

  } else {
    // Gemini
    const r = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,{
      method:'POST', headers:{'Content-Type':'application/json'},
      body:JSON.stringify({ contents:[{parts:[{text:SYS+'\n\n'+prompt}]}],
        generationConfig:{temperature:0.7,maxOutputTokens:4096,responseMimeType:'application/json'} }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); if(prelimIsRealQuota(r.status,e)) throw new Error('QUOTA'); throw new Error(e.error?.message||'HTTP '+r.status); }
    const d=await r.json();
    try{ return d.candidates[0].content.parts[0].text||''; }
    catch(_){ throw new Error('Unexpected Gemini response'); }
  }
}

/* ── Generate one prelim part with automatic key-rotation on real quota hits,
   and a couple of retries (with a short backoff) on transient/malformed-JSON
   errors. Uses the shared parseAIJson() repair pass — same one the Lesson
   Plan and Summative generators use — instead of a bare JSON.parse, so a
   stray trailing comma or smart-quote from the AI no longer kills the whole
   generation with a raw "Unexpected token" JSON error. ── */
async function prelimGenerateOnePart(prompt, label){
  const maxContentAttempts = 3;
  const maxKeyRotates = Math.max(1, mkKeys.length);
  let keyRotates = 0;
  let contentAttempts = 0;

  while(true){
    const apiKey = getActiveKey();
    if(!apiKey) throw new Error('NO_KEY');
    try{
      const raw = await prelimCallAI(prompt, apiKey);
      return parseAIJson(raw);
    } catch(e){
      if(e.message === 'QUOTA'){
        const rotated = markQuota(apiKey);
        keyRotates++;
        if(!rotated || keyRotates > maxKeyRotates){
          throw new Error('QUOTA');
        }
        toast(`🔄 Quota hit on ${label} — switching to the next key…`, 'ti');
        continue; // try again immediately with the newly-active key
      }
      contentAttempts++;
      if(contentAttempts >= maxContentAttempts) throw e;
      await new Promise(r => setTimeout(r, 900 * contentAttempts));
    }
  }
}

/* ── Preview renderer ── */
function prelimRenderPreview(){
  if(!prelimResult) return;
  const { part1, part2, part3, subject, grade, quarter, isFil } = prelimResult;

  const p1Label = isFil ? 'Bahagi I. Tama o Mali' : 'Part I. True or False';
  const p2Label = isFil ? 'Bahagi II. Word Bank' : 'Part II. Word Bank';
  const p3Label = isFil ? 'Bahagi III. Sanaysay (Essay)' : 'Part III. Essay';
  const tfInstr = isFil
    ? `Kwento: <em>${esc(part1.story||'')}</em><br>Sumulat ng <strong>T</strong> kung tama at <strong>M</strong> kung mali.`
    : `Story: <em>${esc(part1.story||'')}</em><br>Write <strong>T</strong> if the statement is correct and <strong>F</strong> if it is wrong.`;
  const wbInstr = isFil
    ? `Kwento: <em>${esc(part2.story||'')}</em><br>Gamitin ang mga salita sa <strong>Word Bank</strong> para sagutan ang mga patlang.`
    : `Story: <em>${esc(part2.story||'')}</em><br>Use the words in the <strong>Word Bank</strong> to answer the blanks.`;
  const essayInstr = isFil
    ? `Kwento: <em>${esc(part3.story||'')}</em><br>Sagutin sa 1-2 pangungusap.`
    : `Story: <em>${esc(part3.story||'')}</em><br>Answer in 1-2 sentences.`;

  const items1 = (part1.items||[]).map((it,i)=>
    `<div style="margin:2px 0;">_____ ${i+1}. ${esc(it.q)}</div>`).join('');
  const wb = (part2.wordBank||[]).map(w=>`<strong>${esc(w)}</strong>`).join(' • ');
  const items2 = (part2.items||[]).map((it,i)=>
    `<div style="margin:2px 0;">${i+1}. ${esc(it.q)}</div>`).join('');
  const items3 = (part3.items||[]).map((it,i)=>
    `<div style="margin:4px 0;"><strong>${i+1}.</strong> ${esc(it.q)}<br>
    <div style="border-bottom:1px solid #ccc;margin:3px 0;height:18px;"></div>
    <div style="border-bottom:1px solid #ccc;margin:3px 0;height:18px;"></div></div>`).join('');

  document.getElementById('prelimPreviewBody').innerHTML = `
    <div style="text-align:center;font-weight:900;font-size:14px;">UPPER KLINAN SDA SCHOOL INC</div>
    <div style="text-align:center;font-size:11px;">Purok Mabinuligon, Upper Klinan, Polomolok, South Cotabato</div>
    <div style="text-align:center;font-size:11px;margin-bottom:6px;">School ID: 409417 &nbsp;•&nbsp; "Where Children Enjoy Holistic Learning"</div>
    <div style="text-align:center;font-weight:700;">${esc(quarter)} Quarter Prelim Exam &nbsp;|&nbsp; SY 2025-2026</div>
    <div style="text-align:center;font-weight:700;margin-bottom:8px;">${esc(subject)}</div>
    <div style="margin-bottom:8px;">Name: ___________________________________ &nbsp; Date: _________ &nbsp; Score: _________</div>
    <hr style="margin:8px 0;">
    <div style="font-weight:700;margin:8px 0;">${p1Label} (${(part1.items||[]).length} pts)</div>
    <div style="font-style:italic;font-size:11px;margin-bottom:6px;">${tfInstr}</div>
    ${items1}
    <hr style="margin:8px 0;">
    <div style="font-weight:700;margin:8px 0;">${p2Label} (${(part2.items||[]).length} pts)</div>
    <div style="font-style:italic;font-size:11px;margin-bottom:4px;">${wbInstr}</div>
    <div style="margin-bottom:6px;"><strong>${isFil?'Listahan ng Salita':'Word Bank'}:</strong> ${wb}</div>
    ${items2}
    <hr style="margin:8px 0;">
    <div style="font-weight:700;margin:8px 0;">${p3Label} (${(part3.items||[]).length} items)</div>
    <div style="font-style:italic;font-size:11px;margin-bottom:6px;">${essayInstr}</div>
    ${items3}
  `;
  document.getElementById('prelimPreview').style.display = 'block';

  /* Populate answer key panel */
  const ak1 = (part1.items||[]).map((it,i) =>
    `<div><strong>${i+1}.</strong> ${(it.answer===true||it.answer==='true') ? (isFil?'T (Tama)':'T (True)') : (it.answer===false||it.answer==='false') ? (isFil?'M (Mali)':'F (False)') : esc(String(it.answer||''))}</div>`
  ).join('');
  const ak2 = (part2.items||[]).map((it,i) =>
    `<div><strong>${i+1}.</strong> ${esc(it.answer||'—')}</div>`
  ).join('');
  const akHtml = `
    <div style="font-weight:700;color:#E65100;margin:6px 0 3px;">${p1Label}:</div>
    <div style="columns:2;column-gap:20px;margin-bottom:10px;">${ak1}</div>
    <div style="font-weight:700;color:#E65100;margin:6px 0 3px;">${p2Label}:</div>
    <div style="columns:2;column-gap:20px;margin-bottom:10px;">${ak2}</div>
    <div style="font-weight:700;color:#888;margin:6px 0 3px;">${p3Label}: <em style="font-weight:400;">(Open-ended — check model answers in the downloaded Word file)</em></div>
  `;
  const akBody = document.getElementById('prelimAnsKeyBody');
  if(akBody) akBody.innerHTML = akHtml;
  /* Reset toggle button */
  const akWrap = document.getElementById('prelimAnsKeyWrap');
  const akBtn  = document.getElementById('prelimAnsKeyToggle');
  if(akWrap){ akWrap.style.display = 'none'; }
  if(akBtn) { akBtn.textContent = '👁 Show Answer Key'; }
}

/* ── Toggle prelim answer key ── */
function prelimToggleAnsKey(){
  const wrap = document.getElementById('prelimAnsKeyWrap');
  const btn  = document.getElementById('prelimAnsKeyToggle');
  if(!wrap) return;
  const show = wrap.style.display === 'none';
  wrap.style.display = show ? 'block' : 'none';
  btn.textContent    = show ? '🙈 Hide Answer Key' : '👁 Show Answer Key';
}

/* ── DOCX Download ──
   Rewritten to build the file the SAME reliable way every other export in
   this app does (Lesson Plan, Summative, TOS, Final Exam): hand-written
   WordprocessingML XML wrapped in a Blob, no external library required.
   The previous version depended on loading the third-party "docx" npm
   package from a CDN at click-time — if that script failed to load (network
   hiccup, ad-blocker, CSP, CDN outage) the whole function threw BEFORE
   reaching its own try/catch, so the button did nothing and no error ever
   reached the user. Removing that dependency fixes the silent failure. ── */
async function prelimDownload(){
  if(!prelimResult){ toast('Generate the exam first.','te'); return; }

  try {

  const { part1: part1raw, part2: part2raw, part3: part3raw, subject, grade, quarter, isFil } = prelimResult;
  const part1 = part1raw || { items: [] };
  const part2 = part2raw || { items: [], wordBank: [] };
  const part3 = part3raw || { items: [] };

  const x = s => String(s || '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&apos;');

  const para = (text, opts = {}) => {
    const { bold = false, italic = false, color = '', center = false, sz = 22 } = opts;
    return `<w:p><w:pPr>${center ? '<w:jc w:val="center"/>' : ''}</w:pPr>
      <w:r><w:rPr>${bold ? '<w:b/>' : ''}${italic ? '<w:i/>' : ''}${color ? `<w:color w:val="${color}"/>` : ''}
      <w:sz w:val="${sz}"/><w:szCs w:val="${sz}"/><w:rFonts w:val="Times New Roman"/></w:rPr>
      <w:t xml:space="preserve">${x(text)}</w:t></w:r></w:p>`;
  };

  // Two-run paragraph (label in bold + value in italics), used for the "Story:" lines.
  const paraLabelValue = (label, value, opts = {}) => {
    const { sz = 22 } = opts;
    return `<w:p><w:pPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="${sz}"/><w:szCs w:val="${sz}"/><w:rFonts w:val="Times New Roman"/></w:rPr>
      <w:t xml:space="preserve">${x(label)}</w:t></w:r>
      <w:r><w:rPr><w:i/><w:sz w:val="${sz}"/><w:szCs w:val="${sz}"/><w:rFonts w:val="Times New Roman"/></w:rPr>
      <w:t xml:space="preserve">${x(value)}</w:t></w:r></w:p>`;
  };

  const rule = () => para('— — — — — — — — — — — — — — — — — — — — — — — — — — — —', { center: true, color: 'AAAAAA', sz: 16 });

  const blankLine = () => para('_'.repeat(90), { sz: 20 });

  const p1Label = isFil ? 'Bahagi I. Tama o Mali' : 'Part I. True or False';
  const p2Label = isFil ? 'Bahagi II. Word Bank' : 'Part II. Word Bank';
  const p3Label = isFil ? 'Bahagi III. Sanaysay (Essay)' : 'Part III. Essay';
  const tfPts    = (part1.items || []).length;
  const wbPts    = (part2.items || []).length;
  const essayPts = (part3.items || []).length;

  const tfInstr = isFil
    ? 'Sumulat ng T kung tama at M kung mali.'
    : 'Write T if the statement is correct and F if it is wrong.';
  const wbInstr = isFil
    ? 'Gamitin ang mga salita sa Word Bank para sagutan ang mga patlang. Isulat ang tamang salita sa patlang.'
    : 'Use the words in the Word Bank to answer the blanks. Write the correct word on the line.';
  const essayInstr = isFil ? 'Sagutin sa 1-2 pangungusap.' : 'Answer in 1-2 sentences.';

  const gradeLabel = grade || '';

  // ── PART I items ──
  const part1Xml = (part1.items || []).map(it => para(`_____  ${it.q}`, { sz: 22 })).join('');

  // ── PART II items ──
  const part2Xml = (part2.items || []).map((it, i) => para(`${i + 1}.  ${it.q}`, { sz: 22 })).join('');

  // ── PART III items (question + a few blank answer lines) ──
  const part3Xml = (part3.items || []).map((it, i) =>
    para(`${i + 1}. ${it.q}`, { bold: false, sz: 22 }) +
    blankLine() + blankLine() + blankLine() + blankLine()
  ).join('');

  // ── Answer key ──
  const ak1Xml = (part1.items || []).map((it, i) => {
    const ans = (it.answer === true || it.answer === 'true') ? 'T' : 'F';
    return para(`${i + 1}. ${ans}`, { sz: 20 });
  }).join('');
  const ak2Xml = (part2.items || []).map((it, i) => para(`${i + 1}. ${it.answer || ''}`, { sz: 20 })).join('');

  const xml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?mso-application progid="Word.Document"?>
<w:wordDocument xmlns:w="http://schemas.microsoft.com/office/word/2003/wordml"
  xmlns:wx="http://schemas.microsoft.com/office/word/2003/auxHint"
  w:macrosPresent="no" w:embeddedObjPresent="no" w:ocxPresent="no">
<w:body>
  <w:sectPr>
    <w:pgSz w:w="12240" w:h="15840" w:orient="portrait"/>
    <w:pgMar w:top="1080" w:right="1080" w:bottom="1080" w:left="1080"/>
  </w:sectPr>

  ${para('UPPER KLINAN SDA SCHOOL INC', { bold: true, center: true, sz: 28 })}
  ${para('Purok Mabinuligon, Upper Klinan, Polomolok, South Cotabato', { center: true, sz: 20 })}
  ${para('School ID: 409417', { center: true, sz: 20 })}
  ${para('"Where Children Enjoy Holistic Learning"', { center: true, sz: 20, italic: true })}
  ${para(`${quarter} Quarter`, { bold: true, center: true, sz: 24 })}
  ${para('Prelim Exam', { bold: true, center: true, sz: 26 })}
  ${para('SY 2025-2026', { bold: true, center: true, sz: 22 })}
  ${para(`${subject}${gradeLabel ? ' — ' + gradeLabel : ''}`, { bold: true, center: true, sz: 26 })}
  <w:p/>

  ${para('Name: _______________________________________     Date: __________     Score: __________', { sz: 22 })}
  ${rule()}

  ${para(`${p1Label} (${tfPts} pts)`, { bold: true, sz: 24 })}
  ${paraLabelValue('Story: ', part1.story || '')}
  ${para('👉 ' + tfInstr, { sz: 22 })}
  <w:p/>
  ${part1Xml}
  ${rule()}

  ${para(`${p2Label} (${wbPts} pts)`, { bold: true, sz: 24 })}
  ${paraLabelValue('Story: ', part2.story || '')}
  ${para('👉 ' + wbInstr, { sz: 22 })}
  <w:p/>
  ${para(isFil ? 'Listahan ng Salita:' : 'Word Bank:', { bold: true, sz: 22 })}
  ${para((part2.wordBank || []).join('  •  '), { bold: true, sz: 22 })}
  <w:p/>
  ${part2Xml}
  ${rule()}

  ${para(`${p3Label} (${essayPts} items, 5 pts each)`, { bold: true, sz: 24 })}
  ${paraLabelValue('Story: ', part3.story || '')}
  ${para('👉 ' + essayInstr, { sz: 22 })}
  <w:p/>
  ${part3Xml}
  ${rule()}

  ${para(isFil ? 'SUSI SA PAGWAWASTO (Answer Key)' : 'ANSWER KEY', { bold: true, center: true, color: '2E7D32', sz: 24 })}
  <w:p/>
  ${para(`${p1Label}:`, { bold: true, sz: 22 })}
  ${ak1Xml}
  <w:p/>
  ${para(`${p2Label}:`, { bold: true, sz: 22 })}
  ${ak2Xml}
  <w:p/>
  ${para(`${p3Label}: ${isFil ? '(Bukas na sagot — tingnan ang mga modelong sagot)' : '(Open-ended — check model answers manually)'}`, { color: '888888', italic: true, sz: 20 })}
</w:body>
</w:wordDocument>`;

  const blob = new Blob([xml], { type: 'application/msword' });
  const safeSubject = (subject || 'Subject').replace(/[^\w\s-]/g, '').replace(/\s+/g, '_').slice(0, 40);
  const safeQuarter = (quarter || '').replace(/[^\w\s-]/g, '').replace(/\s+/g, '');
  const fname = `${safeSubject}_${safeQuarter}_Prelim_Exam.doc`;
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fname;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1500);
  toast('✅ Prelim Exam downloaded as Word (.doc)!', 'ts');

  } catch (e) {
    console.error(e);
    toast('❌ Download error: ' + (e && e.message ? e.message : e), 'te');
  }
}
/* ── END PRELIM EXAM ── */