/* ============================================================
   PRELIM EXAM MODULE — file upload/extraction (DOCX/PDF),
   AI generation, preview, DOCX export.
   Also contains shared reference-file helpers (feWordXmlToText,
   feHandleFiles, feRenderRefList, feRemoveRef, feBuildRefContext)
   exactly as originally placed.
   ============================================================ */
function prelimHandleDrop(e){
  e.preventDefault();
  document.getElementById('prelimDropZone').style.background='#F9FBE7';
  prelimHandleFiles(e.dataTransfer.files);
}

async function prelimHandleFiles(fileList){
  const files = Array.from(fileList).filter(f => /\.(docx|doc|pdf)$/i.test(f.name));
  if(!files.length){ toast('Please upload .docx, .doc, or .pdf files only.','te'); return; }
  if(files.length + prelimFiles.length > 6){
    toast('Maximum 6 files allowed. Remove some first.','te'); return;
  }
  for(const file of files){
    const text = await prelimExtractDocx(file);
    prelimFiles.push({ name: file.name, text });
  }
  prelimRenderFileList();
}

async function prelimExtractDocx(file){
  const name = file.name.toLowerCase();
  if(name.endsWith('.pdf')){
    return await prelimExtractPDF(file);
  } else {
    // .docx and .doc both use ZIP+XML (modern .doc saved as docx also works; legacy binary .doc falls back gracefully)
    return await prelimExtractDOCX(file);
  }
}

/* Convert a chunk of Word XML (WordML) into clean plain text — every tag
   becomes a line break, so paragraphs/table cells/runs stay separated. */
function feWordXmlToText(xmlText){
  return xmlText
    .replace(/<[^>]+>/g, '\n')
    .replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>')
    .replace(/&apos;/g,"'").replace(/&quot;/g,'"')
    .split('\n').map(s=>s.trim()).filter(Boolean).join('\n');
}

async function prelimExtractDOCX(file){
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = async (e) => {
      try {
        const buf = e.target.result;
        const head = new Uint8Array(buf.slice(0,4));
        const isZip = head[0]===0x50 && head[1]===0x4B; // 'PK' — real .docx (ZIP)

        if(isZip){
          if(typeof JSZip === 'undefined'){
            await new Promise((res, rej) => {
              const s = document.createElement('script');
              s.src = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js';
              s.onload = res; s.onerror = rej;
              document.head.appendChild(s);
            });
          }
          const zip = await JSZip.loadAsync(buf);
          const xmlFile = zip.file('word/document.xml');
          if(!xmlFile){
            resolve('(Legacy .doc format — content may be limited: ' + file.name + ')');
            return;
          }
          const xmlText = await xmlFile.async('text');
          resolve(feWordXmlToText(xmlText));
          return;
        }

        // Not a ZIP — try decoding as WordML 2003 XML (Word-saved-as-XML .doc,
        // e.g. files generated by the Pointers/Lesson Plan tools: starts with
        // <?xml ...?> and/or <?mso-application progid="Word.Document"?>)
        const text = new TextDecoder('utf-8').decode(buf);
        if(/<\?mso-application|<w:wordDocument|<w:t[ >]/i.test(text)){
          resolve(feWordXmlToText(text));
          return;
        }

        resolve('(Legacy binary .doc format not supported — please save/export as .docx or .pdf: ' + file.name + ')');
      } catch(err){
        resolve('(Could not read ' + file.name + ': ' + err.message + ')');
      }
    };
    reader.readAsArrayBuffer(file);
  });
}

async function prelimExtractPDF(file){
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = async (e) => {
      try {
        // Load PDF.js from CDN if not present
        if(typeof pdfjsLib === 'undefined'){
          await new Promise((res, rej) => {
            const s = document.createElement('script');
            s.src = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';
            s.onload = () => {
              pdfjsLib.GlobalWorkerOptions.workerSrc =
                'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
              res();
            };
            s.onerror = rej;
            document.head.appendChild(s);
          });
        }
        const typedArray = new Uint8Array(e.target.result);
        const pdf = await pdfjsLib.getDocument({ data: typedArray }).promise;
        let fullText = '';
        for(let i = 1; i <= pdf.numPages; i++){
          const page = await pdf.getPage(i);
          const tc = await page.getTextContent();
          const pageText = tc.items.map(item => item.str).join(' ');
          fullText += pageText + '\n';
        }
        resolve(fullText.replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim());
      } catch(err){
        resolve('(Could not read PDF ' + file.name + ': ' + err.message + ')');
      }
    };
    reader.readAsArrayBuffer(file);
  });
}

function prelimRenderFileList(){
  const list = document.getElementById('prelimFileList');
  const items = document.getElementById('prelimFileItems');
  if(!prelimFiles.length){ list.style.display='none'; return; }
  list.style.display='block';
  items.innerHTML = prelimFiles.map((f,i) => `
    <div style="display:flex;align-items:center;gap:8px;background:#F1F8E9;border-radius:6px;padding:7px 10px;">
      <span style="font-size:14px;">📄</span>
      <span style="flex:1;font-size:12px;font-weight:600;color:#33691E;">${esc(f.name)}</span>
      <span style="font-size:10px;color:#888;">${f.text.length} chars</span>
      <button onclick="prelimRemoveFile(${i})" style="background:none;border:none;cursor:pointer;color:#C62828;font-size:14px;padding:0 4px;" title="Remove">✕</button>
    </div>`).join('');
}

function prelimRemoveFile(i){
  prelimFiles.splice(i,1);
  prelimRenderFileList();
}

/* ── Final Exam reference files (read by AI; item count/order still from TOS) ── */
let feRefFiles = [];   // [{name, text}]
async function feHandleFiles(fileList){
  const files = Array.from(fileList).filter(f => /\.(docx|doc|pdf)$/i.test(f.name));
  if(!files.length){ toast('Please upload .docx, .doc, or .pdf files only.','te'); return; }
  if(files.length + feRefFiles.length > 6){ toast('Maximum 6 reference files.','te'); return; }
  for(const file of files){
    const text = await prelimExtractDocx(file);   // reuse existing docx/pdf extractor
    feRefFiles.push({ name:file.name, text });
  }
  document.getElementById('feRefInput').value='';
  feRenderRefList();
}
function feRenderRefList(){
  const list = document.getElementById('feRefList');
  if(!list) return;
  list.innerHTML = feRefFiles.map((f,i)=>`
    <div style="display:flex;align-items:center;gap:8px;background:#F1F8E9;border-radius:6px;padding:7px 10px;">
      <span style="font-size:14px;">📄</span>
      <span style="flex:1;font-size:12px;font-weight:600;color:#33691E;">${esc(f.name)}</span>
      <span style="font-size:10px;color:#888;">${f.text.length} chars</span>
      <button onclick="feRemoveRef(${i})" style="background:none;border:none;cursor:pointer;color:#C62828;font-size:14px;padding:0 4px;" title="Remove">✕</button>
    </div>`).join('');
}
function feRemoveRef(i){ feRefFiles.splice(i,1); feRenderRefList(); }
function feBuildRefContext(){
  if(!feRefFiles.length) return '';
  const combined = feRefFiles.map((f,i)=>`--- FILE ${i+1}: ${f.name} ---\n${f.text}`).join('\n\n').slice(0, 12000);
  return combined;
}

/* ── Main generation ── */
async function prelimGenerate(){
  const apiKey = getActiveKey();
  if(!apiKey){ toast('⚠️ No API key. Add one in the API Key Manager.','te'); return; }
  if(prelimFiles.length < 3){ toast('Please upload at least 3 reference files (.docx, .doc, or .pdf).','te'); return; }

  const subject = document.getElementById('prelimSubject').value.trim() || 'the subject';
  const grade   = document.getElementById('prelimGrade').value;
  const quarter = document.getElementById('prelimQuarter').value;
  const tfCount = parseInt(document.getElementById('prelimTF').value) || 20;
  const wbCount = parseInt(document.getElementById('prelimWB').value) || 10;
  const essayCount = parseInt(document.getElementById('prelimEssay').value) || 2;

  const isFil = /\bfilipino\b/i.test(subject) || /\barpan\b/i.test(subject);

  // Build combined context from uploaded files
  const combinedContext = prelimFiles.map((f,i) =>
    `=== FILE ${i+1}: ${f.name} ===\n${f.text.slice(0,3000)}`
  ).join('\n\n');

  const genBtn = document.getElementById('prelimGenBtn');
  const gp = document.getElementById('prelimGP');
  const gfill = document.getElementById('prelimGFill');
  const gstat = document.getElementById('prelimGStat');
  const dlBtn = document.getElementById('prelimDlBtn');

  genBtn.disabled = true;
  genBtn.textContent = '⏳ Generating…';
  gp.style.display = 'block';
  gfill.style.width = '10%';
  dlBtn.style.display = 'none';
  document.getElementById('prelimPreview').style.display = 'none';
  prelimResult = null;

  const lang = isFil ? 'FILIPINO (Tagalog)' : 'ENGLISH';
  const langNote = isFil
    ? 'MAHALAGA: Isulat ang LAHAT ng tanong, salita, at sagot SA FILIPINO/TAGALOG. Angkop sa antas ng Grades 4-6.'
    : 'Write all questions and content in ENGLISH appropriate for Grades 4-6.';

  gstat.textContent = 'Generating Part I — True or False…';
  gfill.style.width = '20%';

  // PART I — True or False
  const prompt1 = isFil ? `
Ikaw ay isang guro na gumagawa ng Prelim Exam para sa ${grade} ${subject} (${quarter} Quarter).
Batay sa mga sumusunod na sangguniang dokumento, gumawa ng eksaktong ${tfCount} True or False na tanong.

KONTEKSTO MULA SA MGA DOKUMENTO:
${combinedContext}

${langNote}

Mga Panuntunan:
- Gumawa ng eksaktong ${tfCount} tanong na True o False
- Ibatay ang lahat ng tanong sa nilalaman ng mga dokumento
- Isama ang pangalan ng kwento/paksa bilang "story" field (halimbawa: "Ang Bahay sa Bato")
- Ang mga tanong ay dapat angkop sa ${grade} na mag-aaral
- Sagutin LAMANG ng valid JSON. Walang markdown, walang backticks.

{
  "story": "Pangalan ng Kwento o Paksa",
  "items": [
    {"q": "Ang tanong dito.", "answer": true},
    {"q": "Isa pang tanong.", "answer": false}
  ]
}` : `
You are a teacher creating a Prelim Exam for ${grade} ${subject} (${quarter} Quarter).
Based on the reference documents below, create exactly ${tfCount} True or False questions.

CONTEXT FROM UPLOADED DOCUMENTS:
${combinedContext}

${langNote}

Rules:
- Create exactly ${tfCount} True/False questions
- Base all questions on content from the documents
- Include the story/topic name as the "story" field
- Questions must be appropriate for ${grade} students
- Respond ONLY with valid JSON. No markdown, no backticks.

{
  "story": "Story or Topic Name",
  "items": [
    {"q": "The question here.", "answer": true},
    {"q": "Another question.", "answer": false}
  ]
}`;

  let part1, part2, part3;

  try {
    gstat.textContent = 'Generating Part I — True or False…';
    gfill.style.width = '25%';
    const raw1 = await prelimCallAI(prompt1, apiKey);
    part1 = JSON.parse(raw1.replace(/```json|```/g,'').trim());

    gstat.textContent = 'Generating Part II — Word Bank…';
    gfill.style.width = '55%';

    const prompt2 = isFil ? `
Batay sa mga sangguniang dokumento, gumawa ng Word Bank (Fill in the Blanks) na may eksaktong ${wbCount} tanong para sa ${grade} ${subject}.

KONTEKSTO:
${combinedContext}

${langNote}

- Gumawa ng ${wbCount} fill-in-the-blank na pangungusap
- Isama ang lahat ng sagot sa isang "wordBank" array (10 salita, maaaring may dagdag na 2-3 na panlito)
- Isama ang pangalan ng kwento/paksa bilang "story" field
- Sagutin LAMANG ng valid JSON.

{
  "story": "Pangalan ng Kwento",
  "wordBank": ["salita1","salita2","salita3"],
  "items": [
    {"q": "Si __________ ay pumunta sa bundok.", "answer": "Juan"}
  ]
}` : `
Based on the reference documents, create a Word Bank exercise with exactly ${wbCount} fill-in-the-blank sentences for ${grade} ${subject}.

CONTEXT:
${combinedContext}

${langNote}

- Create ${wbCount} fill-in-the-blank sentences
- Include all answers in a "wordBank" array (add 2-3 extra distractor words)
- Include the story/topic name as "story" field
- Respond ONLY with valid JSON.

{
  "story": "Story Name",
  "wordBank": ["word1","word2","word3"],
  "items": [
    {"q": "The __________ went to the mountain.", "answer": "man"}
  ]
}`;

    const raw2 = await prelimCallAI(prompt2, apiKey);
    part2 = JSON.parse(raw2.replace(/```json|```/g,'').trim());

    gstat.textContent = 'Generating Part III — Essay…';
    gfill.style.width = '80%';

    const prompt3 = isFil ? `
Batay sa mga sangguniang dokumento, gumawa ng eksaktong ${essayCount} essay na tanong para sa ${grade} ${subject}.

KONTEKSTO:
${combinedContext}

${langNote}

- Ang bawat tanong ay dapat sumagot ng 1-2 pangungusap
- Isama ang pangalan ng kwento/paksa bilang "story" field
- Sagutin LAMANG ng valid JSON.

{
  "story": "Pangalan ng Kwento",
  "items": [
    {"q": "Bakit mahalaga ang... ?"}
  ]
}` : `
Based on the reference documents, create exactly ${essayCount} essay questions for ${grade} ${subject}.

CONTEXT:
${combinedContext}

${langNote}

- Each question should be answered in 1-2 sentences
- Include the story/topic name as "story" field
- Respond ONLY with valid JSON.

{
  "story": "Story Name",
  "items": [
    {"q": "Why is it important that... ?"}
  ]
}`;

    const raw3 = await prelimCallAI(prompt3, apiKey);
    part3 = JSON.parse(raw3.replace(/```json|```/g,'').trim());

    gfill.style.width = '100%';
    gstat.textContent = '✅ Done!';

    prelimResult = { part1, part2, part3, subject, grade, quarter, isFil, tfCount, wbCount, essayCount };
    prelimRenderPreview();
    dlBtn.style.display = '';
    toast('✅ Prelim Exam generated successfully!','ts');
  } catch(e){
    console.error(e);
    toast('❌ Error generating prelim exam: ' + e.message,'te');
    gstat.textContent = '❌ Error: ' + e.message;
  }

  genBtn.disabled = false;
  genBtn.textContent = '🤖 Generate Prelim Exam';
}

/* ── AI call for prelim (uses active provider) ── */
async function prelimCallAI(prompt, apiKey){
  const keyObj = mkKeys[mkActive] || {};
  const provider = feDetectProvider(apiKey, keyObj.provider);
  const SYS = 'Return only valid JSON. No markdown. No backticks. No explanation.';

  if(provider === 'openai' || provider === 'groq'){
    const url = provider==='groq'
      ? 'https://api.groq.com/openai/v1/chat/completions'
      : 'https://api.openai.com/v1/chat/completions';
    const model = provider==='groq' ? 'llama-3.3-70b-versatile' : 'gpt-4o-mini';
    const r = await fetch(url,{ method:'POST', headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey},
      body:JSON.stringify({ model, max_tokens:2048, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); throw new Error(e.error?.message||'HTTP '+r.status); }
    const d=await r.json(); return d.choices?.[0]?.message?.content||'';

  } else if(provider === 'mistral'){
    const r = await fetch('https://api.mistral.ai/v1/chat/completions',{ method:'POST',
      headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey},
      body:JSON.stringify({ model:'mistral-small-latest', max_tokens:2048, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); throw new Error(e.message||e.error?.message||'HTTP '+r.status); }
    const d=await r.json(); return d.choices?.[0]?.message?.content||'';

  } else if(provider === 'deepseek'){
    const r = await fetch('https://api.deepseek.com/v1/chat/completions',{ method:'POST',
      headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey},
      body:JSON.stringify({ model:'deepseek-chat', max_tokens:2048, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); throw new Error(e.error?.message||'HTTP '+r.status); }
    const d=await r.json(); return d.choices?.[0]?.message?.content||'';

  } else if(provider === 'cohere'){
    const r = await fetch('https://api.cohere.com/v2/chat',{ method:'POST',
      headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey},
      body:JSON.stringify({ model:'command-r-plus', max_tokens:2048, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); throw new Error(e.message||'HTTP '+r.status); }
    const d=await r.json(); return d.message?.content?.[0]?.text||'';

  } else if(provider === 'openrouter'){
    const r = await fetch('https://openrouter.ai/api/v1/chat/completions',{ method:'POST',
      headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey,
        'HTTP-Referer':'https://localhost','X-Title':'Prelim Exam Generator'},
      body:JSON.stringify({ model:'openrouter/free', max_tokens:2048, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); throw new Error(e.error?.message||'HTTP '+r.status); }
    const d=await r.json(); return d.choices?.[0]?.message?.content||'';

  } else {
    // Gemini
    const r = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,{
      method:'POST', headers:{'Content-Type':'application/json'},
      body:JSON.stringify({ contents:[{parts:[{text:SYS+'\n\n'+prompt}]}],
        generationConfig:{temperature:0.7,maxOutputTokens:2048,responseMimeType:'application/json'} }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); throw new Error(e.error?.message||'HTTP '+r.status); }
    const d=await r.json();
    try{ return d.candidates[0].content.parts[0].text||''; }
    catch(_){ throw new Error('Unexpected Gemini response'); }
  }
}

/* ── Preview renderer ── */
function prelimRenderPreview(){
  if(!prelimResult) return;
  const { part1, part2, part3, subject, grade, quarter, isFil } = prelimResult;

  const p1Label = isFil ? 'Bahagi I. Tama o Mali' : 'Part I. True or False';
  const p2Label = isFil ? 'Bahagi II. Word Bank' : 'Part II. Word Bank';
  const p3Label = isFil ? 'Bahagi III. Sanaysay (Essay)' : 'Part III. Essay';
  const tfInstr = isFil
    ? `Kwento: <em>${esc(part1.story||'')}</em><br>Sumulat ng <strong>T</strong> kung tama at <strong>M</strong> kung mali.`
    : `Story: <em>${esc(part1.story||'')}</em><br>Write <strong>T</strong> if the statement is correct and <strong>F</strong> if it is wrong.`;
  const wbInstr = isFil
    ? `Kwento: <em>${esc(part2.story||'')}</em><br>Gamitin ang mga salita sa <strong>Word Bank</strong> para sagutan ang mga patlang.`
    : `Story: <em>${esc(part2.story||'')}</em><br>Use the words in the <strong>Word Bank</strong> to answer the blanks.`;
  const essayInstr = isFil
    ? `Kwento: <em>${esc(part3.story||'')}</em><br>Sagutin sa 1-2 pangungusap.`
    : `Story: <em>${esc(part3.story||'')}</em><br>Answer in 1-2 sentences.`;

  const items1 = (part1.items||[]).map((it,i)=>
    `<div style="margin:2px 0;">_____ ${i+1}. ${esc(it.q)}</div>`).join('');
  const wb = (part2.wordBank||[]).map(w=>`<strong>${esc(w)}</strong>`).join(' • ');
  const items2 = (part2.items||[]).map((it,i)=>
    `<div style="margin:2px 0;">${i+1}. ${esc(it.q)}</div>`).join('');
  const items3 = (part3.items||[]).map((it,i)=>
    `<div style="margin:4px 0;"><strong>${i+1}.</strong> ${esc(it.q)}<br>
    <div style="border-bottom:1px solid #ccc;margin:3px 0;height:18px;"></div>
    <div style="border-bottom:1px solid #ccc;margin:3px 0;height:18px;"></div></div>`).join('');

  document.getElementById('prelimPreviewBody').innerHTML = `
    <div style="text-align:center;font-weight:900;font-size:14px;">UPPER KLINAN SDA SCHOOL INC</div>
    <div style="text-align:center;font-size:11px;">Purok Mabinuligon, Upper Klinan, Polomolok, South Cotabato</div>
    <div style="text-align:center;font-size:11px;margin-bottom:6px;">School ID: 409417 &nbsp;•&nbsp; "Where Children Enjoy Holistic Learning"</div>
    <div style="text-align:center;font-weight:700;">${esc(quarter)} Quarter Prelim Exam &nbsp;|&nbsp; SY 2025-2026</div>
    <div style="text-align:center;font-weight:700;margin-bottom:8px;">${esc(subject)}</div>
    <div style="margin-bottom:8px;">Name: ___________________________________ &nbsp; Date: _________ &nbsp; Score: _________</div>
    <hr style="margin:8px 0;">
    <div style="font-weight:700;margin:8px 0;">${p1Label} (${(part1.items||[]).length} pts)</div>
    <div style="font-style:italic;font-size:11px;margin-bottom:6px;">${tfInstr}</div>
    ${items1}
    <hr style="margin:8px 0;">
    <div style="font-weight:700;margin:8px 0;">${p2Label} (${(part2.items||[]).length} pts)</div>
    <div style="font-style:italic;font-size:11px;margin-bottom:4px;">${wbInstr}</div>
    <div style="margin-bottom:6px;"><strong>${isFil?'Listahan ng Salita':'Word Bank'}:</strong> ${wb}</div>
    ${items2}
    <hr style="margin:8px 0;">
    <div style="font-weight:700;margin:8px 0;">${p3Label} (${(part3.items||[]).length} items)</div>
    <div style="font-style:italic;font-size:11px;margin-bottom:6px;">${essayInstr}</div>
    ${items3}
  `;
  document.getElementById('prelimPreview').style.display = 'block';

  /* Populate answer key panel */
  const ak1 = (part1.items||[]).map((it,i) =>
    `<div><strong>${i+1}.</strong> ${(it.answer===true||it.answer==='true') ? (isFil?'T (Tama)':'T (True)') : (it.answer===false||it.answer==='false') ? (isFil?'M (Mali)':'F (False)') : esc(String(it.answer||''))}</div>`
  ).join('');
  const ak2 = (part2.items||[]).map((it,i) =>
    `<div><strong>${i+1}.</strong> ${esc(it.answer||'—')}</div>`
  ).join('');
  const akHtml = `
    <div style="font-weight:700;color:#E65100;margin:6px 0 3px;">${p1Label}:</div>
    <div style="columns:2;column-gap:20px;margin-bottom:10px;">${ak1}</div>
    <div style="font-weight:700;color:#E65100;margin:6px 0 3px;">${p2Label}:</div>
    <div style="columns:2;column-gap:20px;margin-bottom:10px;">${ak2}</div>
    <div style="font-weight:700;color:#888;margin:6px 0 3px;">${p3Label}: <em style="font-weight:400;">(Open-ended — check model answers in the downloaded Word file)</em></div>
  `;
  const akBody = document.getElementById('prelimAnsKeyBody');
  if(akBody) akBody.innerHTML = akHtml;
  /* Reset toggle button */
  const akWrap = document.getElementById('prelimAnsKeyWrap');
  const akBtn  = document.getElementById('prelimAnsKeyToggle');
  if(akWrap){ akWrap.style.display = 'none'; }
  if(akBtn) { akBtn.textContent = '👁 Show Answer Key'; }
}

/* ── Toggle prelim answer key ── */
function prelimToggleAnsKey(){
  const wrap = document.getElementById('prelimAnsKeyWrap');
  const btn  = document.getElementById('prelimAnsKeyToggle');
  if(!wrap) return;
  const show = wrap.style.display === 'none';
  wrap.style.display = show ? 'block' : 'none';
  btn.textContent    = show ? '🙈 Hide Answer Key' : '👁 Show Answer Key';
}

/* ── DOCX Download — matches Bible 4 format exactly ── */
async function prelimDownload(){
  if(!prelimResult){ toast('Generate the exam first.','te'); return; }

  const { part1, part2, part3, subject, grade, quarter, isFil, school } = prelimResult;
  const prepBy = document.getElementById('prepBy')?.value || '';

  // Load docx.js
  if(typeof docx === 'undefined'){
    await new Promise((res,rej) => {
      const s = document.createElement('script');
      s.src = 'https://cdnjs.cloudflare.com/ajax/libs/docx/8.5.0/docx.umd.min.js';
      s.onload=res; s.onerror=rej; document.head.appendChild(s);
    });
  }
  const { Document, Packer, Paragraph, TextRun, AlignmentType, BorderStyle,
          WidthType, UnderlineType, HeadingLevel } = docx;

  const CM = (n) => Math.round(n * 567); // cm to DXA (1cm ≈ 567 DXA)
  const iFont = 'Times New Roman';

  const blank = (len=40) => new TextRun({ text: '_'.repeat(len), underline:{ type: UnderlineType.SINGLE } });
  const sp = (n=1) => new TextRun({ text: ' '.repeat(n) });

  const hdr = (txt, sz=24, bold=true, align=AlignmentType.CENTER) =>
    new Paragraph({ alignment: align, spacing:{ after:0, before:0 },
      children:[new TextRun({ text:txt, bold, size:sz, font:iFont })] });

  const bodyPar = (children, spaceBefore=40, spaceAfter=40, align=AlignmentType.LEFT) =>
    new Paragraph({ alignment: align, spacing:{ before:spaceBefore, after:spaceAfter },
      children });

  const rule = () => new Paragraph({
    spacing:{before:40,after:40},
    border:{ bottom:{ style:BorderStyle.SINGLE, size:6, color:'000000', space:1 } },
    children:[]
  });

  const p1Label = isFil ? 'Bahagi I. Tama o Mali' : 'Part I. True or False';
  const p2Label = isFil ? 'Bahagi II. Word Bank' : 'Part II. Word Bank';
  const p3Label = isFil ? 'Bahagi III. Sanaysay (Essay)' : 'Part III. Essay';
  const tfPts  = (part1.items||[]).length;
  const wbPts  = (part2.items||[]).length;
  const essayPts = (part3.items||[]).length;

  const tfInstr = isFil
    ? `Sumulat ng T kung tama at M kung mali.`
    : `Write T if the statement is correct and F if it is wrong.`;
  const wbInstr = isFil
    ? `Gamitin ang mga salita sa Word Bank para sagutan ang mga patlang. Isulat ang tamang salita sa patlang.`
    : `Use the words in the Word Bank to answer the blanks. Write the correct word on the line.`;
  const essayInstr = isFil
    ? `Sagutin sa 1-2 pangungusap.`
    : `Answer in 1-2 sentences.`;

  const answerLines = (n=9) => Array.from({length:n}, () =>
    new Paragraph({ spacing:{before:20,after:20},
      children:[new TextRun({ text:'_'.repeat(90), size:20, font:iFont })] })
  );

  const children = [
    // ── Header ──
    hdr('UPPER KLINAN SDA SCHOOL INC', 28, true),
    hdr('Purok Mabinuligon, Upper Klinan, Polomolok, South Cotabato', 20, false),
    hdr('School ID: 409417', 20, false),
    hdr('"Where Children Enjoy Holistic Learning"', 20, false),
    hdr(`${quarter} Quarter`, 24, true),
    hdr('Prelim Exam', 26, true),
    hdr('SY 2025-2026', 22, true),
    hdr(subject, 26, true),
    new Paragraph({ spacing:{before:80, after:80},
      children:[
        new TextRun({ text:'Name: ', bold:true, size:22, font:iFont }),
        blank(42),
        sp(4),
        new TextRun({ text:'  Date:', bold:true, size:22, font:iFont }),
        blank(12),
        sp(2),
        new TextRun({ text:'  Score:', bold:true, size:22, font:iFont }),
        blank(12),
      ]}),
    rule(),

    // ── PART I ──
    bodyPar([new TextRun({ text:`${p1Label} (${tfPts} pts)`, bold:true, size:24, font:iFont })], 80, 40),
    bodyPar([
      new TextRun({ text:`Story: `, bold:true, size:22, font:iFont }),
      new TextRun({ text: part1.story||'', italics:true, size:22, font:iFont }),
    ], 20, 20),
    bodyPar([
      new TextRun({ text: '👉 ', size:22, font:iFont }),
      new TextRun({ text: tfInstr, size:22, font:iFont }),
    ], 20, 60),
    ...(part1.items||[]).map(it =>
      new Paragraph({ spacing:{before:30,after:30}, indent:{left:CM(0.5)},
        children:[
          new TextRun({ text:'_____  ', size:22, font:iFont }),
          new TextRun({ text: it.q, size:22, font:iFont }),
        ]})
    ),
    rule(),

    // ── PART II ──
    bodyPar([new TextRun({ text:`${p2Label} (${wbPts} pts)`, bold:true, size:24, font:iFont })], 80, 40),
    bodyPar([
      new TextRun({ text:`Story: `, bold:true, size:22, font:iFont }),
      new TextRun({ text: part2.story||'', italics:true, size:22, font:iFont }),
    ], 20, 20),
    bodyPar([
      new TextRun({ text:'👉 ', size:22, font:iFont }),
      new TextRun({ text: wbInstr, size:22, font:iFont }),
    ], 20, 40),
    // Word Bank box
    bodyPar([
      new TextRun({ text: `${isFil?'Listahan ng Salita':'Word Bank'}:`, bold:true, size:22, font:iFont }),
    ], 20, 10),
    bodyPar([
      new TextRun({ text: (part2.wordBank||[]).join(' • '), bold:true, size:22, font:iFont }),
    ], 10, 40),
    ...(part2.items||[]).map((it,i) =>
      new Paragraph({ spacing:{before:30,after:30}, indent:{left:CM(0.5)},
        children:[
          new TextRun({ text:`${i+1}.  `, bold:true, size:22, font:iFont }),
          new TextRun({ text: it.q, size:22, font:iFont }),
        ]})
    ),
    rule(),

    // ── PART III ──
    bodyPar([new TextRun({ text:`${p3Label} (${essayPts} items 5 pts)`, bold:true, size:24, font:iFont })], 80, 40),
    bodyPar([
      new TextRun({ text:`Story: `, bold:true, size:22, font:iFont }),
      new TextRun({ text: part3.story||'', italics:true, size:22, font:iFont }),
    ], 20, 20),
    bodyPar([
      new TextRun({ text:'👉 ', size:22, font:iFont }),
      new TextRun({ text: essayInstr, size:22, font:iFont }),
    ], 20, 40),
    ...(part3.items||[]).flatMap((it,i) => [
      new Paragraph({ spacing:{before:40,after:20},
        children:[
          new TextRun({ text:`${i+1}. `, bold:true, size:22, font:iFont }),
          new TextRun({ text: it.q, size:22, font:iFont }),
        ]}),
      ...answerLines(9),
      new Paragraph({ spacing:{before:0,after:0}, children:[new TextRun({ text:'.', size:22, font:iFont })] }),
    ]),
    rule(),

    // ── ANSWER KEY ──
    bodyPar([new TextRun({ text: isFil?'SUSI SA PAGWAWASTO (Answer Key)':'ANSWER KEY', bold:true, size:24, font:iFont, color:'2E7D32' })], 80, 40),
    bodyPar([new TextRun({ text: `${p1Label}:`, bold:true, size:22, font:iFont })], 20, 10),
    ...(part1.items||[]).map((it,i) =>
      new Paragraph({ spacing:{before:20,after:20}, indent:{left:CM(0.5)},
        children:[new TextRun({ text:`${i+1}. ${it.answer===true||it.answer==='true'?'T':'F'}`, size:22, font:iFont })] })
    ),
    bodyPar([new TextRun({ text: `${p2Label}:`, bold:true, size:22, font:iFont })], 40, 10),
    ...(part2.items||[]).map((it,i) =>
      new Paragraph({ spacing:{before:20,after:20}, indent:{left:CM(0.5)},
        children:[new TextRun({ text:`${i+1}. ${it.answer||''}`, size:22, font:iFont })] })
    ),
  ];

  try {
    const doc = new Document({
      sections:[{
        properties:{
          page:{
            size:{ width:12240, height:15840 },
            margin:{ top:CM(2), right:CM(2), bottom:CM(2), left:CM(2.5) }
          }
        },
        children
      }]
    });
    const buf = await Packer.toBuffer(doc);
    const blob = new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});
    const fname = `${subject.replace(/\s+/g,'_')}_${quarter}_Prelim_Exam.docx`;
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href=url; a.download=fname; a.click();
    setTimeout(()=>URL.revokeObjectURL(url),1500);
    toast('✅ Prelim Exam downloaded as Word (.docx)!','ts');
  } catch(e){
    console.error(e);
    toast('❌ Download error: '+e.message,'te');
  }
}
/* ── END PRELIM EXAM ── */