/* ============================================================
   PRELIM EXAM MODULE — file upload/extraction (DOCX/PDF),
   AI generation, preview, DOCX export.
   Also contains shared reference-file helpers (feWordXmlToText,
   feHandleFiles, feRenderRefList, feRemoveRef, feBuildRefContext)
   exactly as originally placed.
   ============================================================ */
function prelimHandleDrop(e){
  e.preventDefault();
  document.getElementById('prelimDropZone').style.background='#F9FBE7';
  prelimHandleFiles(e.dataTransfer.files);
}

async function prelimHandleFiles(fileList){
  const files = Array.from(fileList).filter(f => /\.(docx|doc|pdf)$/i.test(f.name));
  if(!files.length){ toast('Please upload .docx, .doc, or .pdf files only.','te'); return; }
  for(const file of files){
    const text = await prelimExtractDocx(file);
    prelimFiles.push({ name: file.name, text });
  }
  prelimRenderFileList();
}

async function prelimExtractDocx(file){
  const name = file.name.toLowerCase();
  if(name.endsWith('.pdf')){
    return await prelimExtractPDF(file);
  } else {
    // .docx and .doc both use ZIP+XML (modern .doc saved as docx also works; legacy binary .doc falls back gracefully)
    return await prelimExtractDOCX(file);
  }
}

/* Convert a chunk of Word XML (WordML) into clean plain text — every tag
   becomes a line break, so paragraphs/table cells/runs stay separated. */
function feWordXmlToText(xmlText){
  return xmlText
    .replace(/<[^>]+>/g, '\n')
    .replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>')
    .replace(/&apos;/g,"'").replace(/&quot;/g,'"')
    .split('\n').map(s=>s.trim()).filter(Boolean).join('\n');
}

async function prelimExtractDOCX(file){
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = async (e) => {
      try {
        const buf = e.target.result;
        const head = new Uint8Array(buf.slice(0,4));
        const isZip = head[0]===0x50 && head[1]===0x4B; // 'PK' — real .docx (ZIP)

        if(isZip){
          if(typeof JSZip === 'undefined'){
            await new Promise((res, rej) => {
              const s = document.createElement('script');
              s.src = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js';
              s.onload = res; s.onerror = rej;
              document.head.appendChild(s);
            });
          }
          const zip = await JSZip.loadAsync(buf);
          const xmlFile = zip.file('word/document.xml');
          if(!xmlFile){
            resolve('(Legacy .doc format — content may be limited: ' + file.name + ')');
            return;
          }
          const xmlText = await xmlFile.async('text');
          resolve(feWordXmlToText(xmlText));
          return;
        }

        // Not a ZIP — try decoding as WordML 2003 XML (Word-saved-as-XML .doc,
        // e.g. files generated by the Pointers/Lesson Plan tools: starts with
        // <?xml ...?> and/or <?mso-application progid="Word.Document"?>)
        const text = new TextDecoder('utf-8').decode(buf);
        if(/<\?mso-application|<w:wordDocument|<w:t[ >]/i.test(text)){
          resolve(feWordXmlToText(text));
          return;
        }

        resolve('(Legacy binary .doc format not supported — please save/export as .docx or .pdf: ' + file.name + ')');
      } catch(err){
        resolve('(Could not read ' + file.name + ': ' + err.message + ')');
      }
    };
    reader.readAsArrayBuffer(file);
  });
}

async function prelimExtractPDF(file){
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = async (e) => {
      try {
        // Load PDF.js from CDN if not present
        if(typeof pdfjsLib === 'undefined'){
          await new Promise((res, rej) => {
            const s = document.createElement('script');
            s.src = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';
            s.onload = () => {
              pdfjsLib.GlobalWorkerOptions.workerSrc =
                'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
              res();
            };
            s.onerror = rej;
            document.head.appendChild(s);
          });
        }
        const typedArray = new Uint8Array(e.target.result);
        const pdf = await pdfjsLib.getDocument({ data: typedArray }).promise;
        let fullText = '';
        for(let i = 1; i <= pdf.numPages; i++){
          const page = await pdf.getPage(i);
          const tc = await page.getTextContent();
          const pageText = tc.items.map(item => item.str).join(' ');
          fullText += pageText + '\n';
        }
        resolve(fullText.replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim());
      } catch(err){
        resolve('(Could not read PDF ' + file.name + ': ' + err.message + ')');
      }
    };
    reader.readAsArrayBuffer(file);
  });
}

function prelimRenderFileList(){
  const list = document.getElementById('prelimFileList');
  const items = document.getElementById('prelimFileItems');
  if(!prelimFiles.length){ list.style.display='none'; return; }
  list.style.display='block';
  items.innerHTML = prelimFiles.map((f,i) => `
    <div style="display:flex;align-items:center;gap:8px;background:#F1F8E9;border-radius:6px;padding:7px 10px;">
      <span style="font-size:14px;">📄</span>
      <span style="flex:1;font-size:12px;font-weight:600;color:#33691E;">${esc(f.name)}</span>
      <span style="font-size:10px;color:#888;">${f.text.length} chars</span>
      <button onclick="prelimRemoveFile(${i})" style="background:none;border:none;cursor:pointer;color:#C62828;font-size:14px;padding:0 4px;" title="Remove">✕</button>
    </div>`).join('');
}

function prelimRemoveFile(i){
  prelimFiles.splice(i,1);
  prelimRenderFileList();
}

/* ── Final Exam reference files (read by AI; item count/order still from TOS) ── */
let feRefFiles = [];   // [{name, text}]
async function feHandleFiles(fileList){
  const files = Array.from(fileList).filter(f => /\.(docx|doc|pdf)$/i.test(f.name));
  if(!files.length){ toast('Please upload .docx, .doc, or .pdf files only.','te'); return; }
  if(files.length + feRefFiles.length > 6){ toast('Maximum 6 reference files.','te'); return; }
  for(const file of files){
    const text = await prelimExtractDocx(file);   // reuse existing docx/pdf extractor
    feRefFiles.push({ name:file.name, text });
  }
  document.getElementById('feRefInput').value='';
  feRenderRefList();
}
function feRenderRefList(){
  const list = document.getElementById('feRefList');
  if(!list) return;
  list.innerHTML = feRefFiles.map((f,i)=>`
    <div style="display:flex;align-items:center;gap:8px;background:#F1F8E9;border-radius:6px;padding:7px 10px;">
      <span style="font-size:14px;">📄</span>
      <span style="flex:1;font-size:12px;font-weight:600;color:#33691E;">${esc(f.name)}</span>
      <span style="font-size:10px;color:#888;">${f.text.length} chars</span>
      <button onclick="feRemoveRef(${i})" style="background:none;border:none;cursor:pointer;color:#C62828;font-size:14px;padding:0 4px;" title="Remove">✕</button>
    </div>`).join('');
}
function feRemoveRef(i){ feRefFiles.splice(i,1); feRenderRefList(); }
function feBuildRefContext(){
  if(!feRefFiles.length) return '';
  const combined = feRefFiles.map((f,i)=>`--- FILE ${i+1}: ${f.name} ---\n${f.text}`).join('\n\n').slice(0, 12000);
  return combined;
}

/* ── Test-type selection (same options as Summative) ── */
let prelimCustomAnswers = { 1: [], 2: [], 3: [] };

function prelimOnTypeChange(slot, val){
  if(val === CUSTOM_ANSWER_TYPE){
    const existing = (prelimCustomAnswers[slot] || []).join(', ');
    const input = prompt('Type the answers pupils should give for this part (2 to 6 answers, separated by commas):', existing);
    if(input === null){ return; }
    const answers = input.split(',').map(a => a.trim()).filter(Boolean);
    if(answers.length < 2 || answers.length > 6){
      toast('Please enter between 2 and 6 answers.','te');
      return;
    }
    prelimCustomAnswers[slot] = answers;
  }
}

function prelimShuffleArray(arr){
  const a = arr.slice();
  for(let k=a.length-1;k>0;k--){ const j=Math.floor(Math.random()*(k+1)); [a[k],a[j]]=[a[j],a[k]]; }
  return a;
}

/* Same rationale as the Summative Test module: AI models tend to place
   correct answers in predictable positions/order — Matching Type letters
   in particular came back with the correct answer ALWAYS the same letter
   as the row number (row 1→A, row 2→B, ...) since nothing shuffled them.
   Multiple Choice also tends to cluster the correct option in the same
   slot, and True/False items in a too-regular sequence. This randomizes
   all of that AFTER generation, without changing any answer content, so
   pupils can't exploit the pattern. Returns the (possibly reordered)
   items plus, for Matching Type, a matchOrder/matchLetterMap the preview
   and docx export both read from so the exam and answer key always agree. */
function prelimRandomizeItems(type, items){
  if(type === 'Multiple Choice'){
    items.forEach(it => {
      if(Array.isArray(it.choices) && it.choices.length > 1) it.choices = prelimShuffleArray(it.choices);
    });
    return { items, matchOrder: null, matchLetterMap: null };
  }
  if(type === 'Matching Type'){
    const order = prelimShuffleArray(items.map((_,i)=>i));
    const matchLetterMap = {};
    order.forEach((origIdx, slotIdx) => { matchLetterMap[origIdx] = String.fromCharCode(65+slotIdx); });
    return { items, matchOrder: order, matchLetterMap };
  }
  if(type === 'True or False' || type === 'True or False (Write the Correct Answer)' || type === CUSTOM_ANSWER_TYPE){
    return { items: prelimShuffleArray(items), matchOrder: null, matchLetterMap: null };
  }
  return { items, matchOrder: null, matchLetterMap: null };
}

/* Type-specific instructions reused across all 3 parts (mirrors Summative's per-type hints) */
function prelimTypeInstructions(type, count, isFil, customAnswers){
  const list = (customAnswers||[]).map(a=>'"'+a+'"').join(', ');
  if(isFil){
    switch(type){
      case 'True or False': return `Gumawa ng eksaktong ${count} pahayag na maaaring TAMA o MALI. Ang "answer" ay dapat boolean true o false.`;
      case 'True or False (Write the Correct Answer)': return `Gumawa ng eksaktong ${count} pahayag. Kung TAMA, ang "answer" ay "Tama". Kung MALI, ang "answer" ay ang WASTONG/tamang pahayag (HUWAG gamitin ang salitang "Mali" bilang sagot).`;
      case 'Multiple Choice': return `Gumawa ng eksaktong ${count} tanong. Bawat isa ay may "choices" array ng 4 na pagpipilian (walang A/B/C/D prefix). Isang tamang sagot lamang; ang "answer" ay eksaktong kopya ng tamang pagpipilian.`;
      case 'Matching Type': return `Gumawa ng eksaktong ${count} pares ng pagtutugma. Ang "q" ay Column A (termino/tanong), ang "columnB" ay ang tamang Column B na tugma; ang "answer" ay kopya rin ng columnB.`;
      case 'Word Bank': return `Magdagdag ng top-level "wordBank" array na may ${count} salitang sagot (dagdagan ng 2-3 panlito). Bawat "q" ay pangungusap na may patlang (__________); ang "answer" ay ang tamang salita.`;
      case 'Enumeration': return `Gumawa ng eksaktong ${count} tanong na nagpapabuo ng listahan (halimbawa: "Ibigay ang 3 bahagi ng..."). Ang "answer" ay ang kumpletong listahan, pinaghihiwalay ng kuwit.`;
      case 'Essay / Extended Response': return `Gumawa ng eksaktong ${count} tanong na sasagutin sa 1-2 pangungusap.`;
      case CUSTOM_ANSWER_TYPE: return `Gumawa ng eksaktong ${count} tanong na ang tamang sagot ay eksaktong isa lamang sa mga sumusunod: ${list || '(walang ibinigay na sagot)'}. Ang "answer" ay eksaktong kopya ng napiling sagot.`;
      default: return `Gumawa ng eksaktong ${count} tanong.`;
    }
  }
  switch(type){
    case 'True or False': return `Create exactly ${count} True/False statements. "answer" must be boolean true or false.`;
    case 'True or False (Write the Correct Answer)': return `Create exactly ${count} statements. If TRUE, "answer" is "True". If FALSE, "answer" must be the corrected true statement (never the word "False").`;
    case 'Multiple Choice': return `Create exactly ${count} questions, each with a "choices" array of exactly 4 plain options (no A/B/C/D prefixes). Exactly one correct; "answer" is an exact copy of the correct choice text.`;
    case 'Matching Type': return `Create exactly ${count} matching pairs. "q" is the Column A term/question, "columnB" is its correct Column B match; "answer" also copies columnB.`;
    case 'Word Bank': return `Include a top-level "wordBank" array with ${count} answer words (plus 2-3 distractors). Each "q" is a fill-in-the-blank sentence (__________); "answer" is the correct word.`;
    case 'Enumeration': return `Create exactly ${count} enumeration prompts asking pupils to list several related items. "answer" contains the full list, comma-separated.`;
    case 'Essay / Extended Response': return `Create exactly ${count} essay questions answerable in 1-2 sentences.`;
    case CUSTOM_ANSWER_TYPE: return `Create exactly ${count} questions whose correct answer is EXACTLY one of: ${list || '(no answers provided)'}. "answer" must copy the chosen answer exactly.`;
    default: return `Create exactly ${count} questions.`;
  }
}

function prelimBuildPartPrompt(type, count, subject, grade, quarter, combinedContext, isFil, customAnswers){
  const langNote = isFil
    ? 'MAHALAGA: Isulat ang LAHAT ng tanong, salita, at sagot SA FILIPINO/TAGALOG. Angkop sa antas ng Grades 4-6.'
    : 'Write all questions and content in ENGLISH appropriate for Grades 4-6.';
  const instr = prelimTypeInstructions(type, count, isFil, customAnswers);
  const shape = `{"q": "..."${type==='Multiple Choice' ? ', "choices": ["...","...","...","..."]' : ''}${type==='Matching Type' ? ', "columnB": "..."' : ''}, "answer": ${type==='True or False' ? 'true' : '"..."'}}`;
  const wbNote = type==='Word Bank' ? (isFil ? '"wordBank": ["salita1","salita2"],\n  ' : '"wordBank": ["word1","word2"],\n  ') : '';
  return isFil ? `
Ikaw ay isang guro na gumagawa ng Prelim Exam (${type}) para sa ${grade} ${subject} (${quarter} Quarter).
Batay sa mga sumusunod na sangguniang dokumento:

${combinedContext}

${langNote}

${instr}
- Isama ang pangalan ng kwento/paksa bilang "story" field.
- Sagutin LAMANG ng valid JSON. Walang markdown, walang backticks.

{
  "story": "Pangalan ng Kwento o Paksa",
  ${wbNote}"items": [
    ${shape}
  ]
}` : `
You are a teacher creating a Prelim Exam part (${type}) for ${grade} ${subject} (${quarter} Quarter).
Based on the reference documents below:

${combinedContext}

${langNote}

${instr}
- Include the story/topic name as the "story" field.
- Respond ONLY with valid JSON. No markdown, no backticks.

{
  "story": "Story or Topic Name",
  ${wbNote}"items": [
    ${shape}
  ]
}`;
}

/* ── Main generation ── */
async function prelimGenerate(){
  const apiKey = getActiveKey();
  if(!apiKey){ toast('⚠️ No API key. Add one in the API Key Manager.','te'); return; }
  if(prelimFiles.length < 1){ toast('Please upload at least 1 reference file (.docx, .doc, or .pdf).','te'); return; }

  const subject = document.getElementById('prelimSubject').value.trim() || 'the subject';
  const grade   = document.getElementById('prelimGrade').value;
  const quarter = document.getElementById('prelimQuarter').value;
  const isFil = /\bfilipino\b/i.test(subject) || /\barpan\b/i.test(subject);

  const slots = [1,2,3].map(slot => {
    const type  = (document.getElementById('prelimType'+slot)||{}).value || '';
    const count = parseInt((document.getElementById('prelimCount'+slot)||{}).value) || 0;
    return { slot, type, count };
  }).filter(s => s.type && s.count > 0);

  if(!slots.length){ toast('Select at least Part I test type and item count.','te'); return; }

  const missingCustom = slots.some(s => s.type === CUSTOM_ANSWER_TYPE && (prelimCustomAnswers[s.slot]||[]).length < 2);
  if(missingCustom){ toast('Set the 2–6 answers for the Custom Answer Set part first.','te'); return; }

  // Build combined context from uploaded files
  const combinedContext = prelimFiles.map((f,i) =>
    `=== FILE ${i+1}: ${f.name} ===\n${f.text.slice(0,3000)}`
  ).join('\n\n');

  const genBtn = document.getElementById('prelimGenBtn');
  const gp = document.getElementById('prelimGP');
  const gfill = document.getElementById('prelimGFill');
  const gstat = document.getElementById('prelimGStat');
  const dlBtn = document.getElementById('prelimDlBtn');

  genBtn.disabled = true;
  genBtn.textContent = '⏳ Generating…';
  gp.style.display = 'block';
  gfill.style.width = '10%';
  dlBtn.style.display = 'none';
  document.getElementById('prelimPreview').style.display = 'none';
  prelimResult = null;

  const parts = [];
  try {
    for(let i=0;i<slots.length;i++){
      const s = slots[i];
      gstat.textContent = `Generating Part ${['I','II','III'][i]} — ${s.type}…`;
      gfill.style.width = Math.round(((i+0.5)/slots.length)*90) + '%';
      const prompt = prelimBuildPartPrompt(s.type, s.count, subject, grade, quarter, combinedContext, isFil, prelimCustomAnswers[s.slot]);
      const data = await prelimGenerateOnePart(prompt, 'Part '+(i+1));
      const rnd = prelimRandomizeItems(s.type, data.items||[]);
      parts.push({ type: s.type, count: s.count, story: data.story||'', items: rnd.items, wordBank: data.wordBank||[], matchOrder: rnd.matchOrder, matchLetterMap: rnd.matchLetterMap });
    }

    gfill.style.width = '100%';
    gstat.textContent = '✅ Done!';

    prelimResult = { parts, subject, grade, quarter, isFil };
    prelimRenderPreview();
    dlBtn.style.display = '';
    toast('✅ Prelim Exam generated successfully!','ts');
  } catch(e){
    console.error(e);
    if(e.message === 'QUOTA'){
      toast('🚫 All API keys hit their quota. Add a new key, or wait a bit and reset quotas in the API Key Manager, then try again.','te');
      gstat.textContent = '🚫 All keys hit quota — add/reset a key and try again.';
    } else if(e.message === 'NO_KEY'){
      toast('⚠️ No usable API key left. Add or reset one in the API Key Manager.','te');
      gstat.textContent = '⚠️ No usable API key.';
    } else {
      toast('❌ Error generating prelim exam: ' + e.message,'te');
      gstat.textContent = '❌ Error: ' + e.message;
    }
  }

  genBtn.disabled = false;
  genBtn.textContent = '🤖 Generate Prelim Exam';
}

/* ── AI call for prelim (uses active provider) ──
   Detects REAL quota/rate-limit signals (HTTP 429 or documented quota codes)
   and throws Error('QUOTA') so the caller can rotate to the next key —
   matching how the Final Exam and Lesson Plan generators already behave.
   Any other failure throws a normal Error with the provider's message. ── */
function prelimIsRealQuota(status, errBody){
  if(status === 429) return true;
  const code = String(errBody?.error?.code || errBody?.error?.type || '').toLowerCase();
  const msg  = String(errBody?.error?.message || errBody?.message || '').toLowerCase();
  return (
    code.includes('rate_limit_exceeded') ||
    code.includes('insufficient_quota') ||
    code.includes('quota_exceeded') ||
    msg.includes('rate limit exceeded') ||
    msg.includes('insufficient_quota') ||
    msg.includes('you exceeded your current quota') ||
    msg.includes('requests per minute') ||
    msg.includes('requests per day') ||
    msg.includes('tokens per minute') ||
    msg.includes('too many requests')
  );
}
async function prelimCallAI(prompt, apiKey){
  const keyObj = mkKeys[mkActive] || {};
  const provider = feDetectProvider(apiKey, keyObj.provider);
  const SYS = 'Return only valid JSON. No markdown. No backticks. No explanation.';

  if(provider === 'openai' || provider === 'groq'){
    const url = provider==='groq'
      ? 'https://api.groq.com/openai/v1/chat/completions'
      : 'https://api.openai.com/v1/chat/completions';
    const model = provider==='groq' ? 'llama-3.3-70b-versatile' : 'gpt-4o-mini';
    const r = await fetch(url,{ method:'POST', headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey},
      body:JSON.stringify({ model, max_tokens:4096, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); if(prelimIsRealQuota(r.status,e)) throw new Error('QUOTA'); throw new Error(e.error?.message||'HTTP '+r.status); }
    const d=await r.json(); return d.choices?.[0]?.message?.content||'';

  } else if(provider === 'mistral'){
    const r = await fetch('https://api.mistral.ai/v1/chat/completions',{ method:'POST',
      headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey},
      body:JSON.stringify({ model:'mistral-small-latest', max_tokens:4096, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); if(prelimIsRealQuota(r.status,e)) throw new Error('QUOTA'); throw new Error(e.message||e.error?.message||'HTTP '+r.status); }
    const d=await r.json(); return d.choices?.[0]?.message?.content||'';

  } else if(provider === 'deepseek'){
    const r = await fetch('https://api.deepseek.com/v1/chat/completions',{ method:'POST',
      headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey},
      body:JSON.stringify({ model:'deepseek-chat', max_tokens:4096, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); if(prelimIsRealQuota(r.status,e)) throw new Error('QUOTA'); throw new Error(e.error?.message||'HTTP '+r.status); }
    const d=await r.json(); return d.choices?.[0]?.message?.content||'';

  } else if(provider === 'cohere'){
    const r = await fetch('https://api.cohere.com/v2/chat',{ method:'POST',
      headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey},
      body:JSON.stringify({ model:'command-r-plus', max_tokens:4096, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); if(prelimIsRealQuota(r.status,e)) throw new Error('QUOTA'); throw new Error(e.message||'HTTP '+r.status); }
    const d=await r.json(); return d.message?.content?.[0]?.text||'';

  } else if(provider === 'openrouter'){
    const r = await fetch('https://openrouter.ai/api/v1/chat/completions',{ method:'POST',
      headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey,
        'HTTP-Referer':'https://localhost','X-Title':'Prelim Exam Generator'},
      body:JSON.stringify({ model:'openrouter/free', max_tokens:2048, temperature:0.7,
        messages:[{role:'system',content:SYS},{role:'user',content:prompt}] }) });
    if(!r.ok){
      const e=await r.json().catch(()=>({}));
      const raw = e.error?.metadata?.raw;
      const inner = raw ? (() => { try { return JSON.parse(raw); } catch(_){ return null; } })() : null;
      if(prelimIsRealQuota(r.status, inner||e)) throw new Error('QUOTA');
      throw new Error(inner?.error?.message || e.error?.message || 'HTTP '+r.status);
    }
    const d=await r.json(); return d.choices?.[0]?.message?.content||'';

  } else {
    // Gemini
    const r = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,{
      method:'POST', headers:{'Content-Type':'application/json'},
      body:JSON.stringify({ contents:[{parts:[{text:SYS+'\n\n'+prompt}]}],
        generationConfig:{temperature:0.7,maxOutputTokens:4096,responseMimeType:'application/json'} }) });
    if(!r.ok){ const e=await r.json().catch(()=>({})); if(prelimIsRealQuota(r.status,e)) throw new Error('QUOTA'); throw new Error(e.error?.message||'HTTP '+r.status); }
    const d=await r.json();
    try{ return d.candidates[0].content.parts[0].text||''; }
    catch(_){ throw new Error('Unexpected Gemini response'); }
  }
}

/* ── Generate one prelim part with automatic key-rotation on real quota hits,
   and a couple of retries (with a short backoff) on transient/malformed-JSON
   errors. Uses the shared parseAIJson() repair pass — same one the Lesson
   Plan and Summative generators use — instead of a bare JSON.parse, so a
   stray trailing comma or smart-quote from the AI no longer kills the whole
   generation with a raw "Unexpected token" JSON error. ── */
async function prelimGenerateOnePart(prompt, label){
  const maxContentAttempts = 3;
  const maxKeyRotates = Math.max(1, mkKeys.length);
  let keyRotates = 0;
  let contentAttempts = 0;

  while(true){
    const apiKey = getActiveKey();
    if(!apiKey) throw new Error('NO_KEY');
    try{
      const raw = await prelimCallAI(prompt, apiKey);
      return parseAIJson(raw);
    } catch(e){
      if(e.message === 'QUOTA'){
        const rotated = markQuota(apiKey);
        keyRotates++;
        if(!rotated || keyRotates > maxKeyRotates){
          throw new Error('QUOTA');
        }
        toast(`🔄 Quota hit on ${label} — switching to the next key…`, 'ti');
        continue; // try again immediately with the newly-active key
      }
      contentAttempts++;
      if(contentAttempts >= maxContentAttempts) throw e;
      await new Promise(r => setTimeout(r, 900 * contentAttempts));
    }
  }
}

/* ── Preview helpers (per test-type rendering, same options as Summative) ── */
function prelimPreviewInstruction(type, isFil){
  const map = {
    'True or False': isFil ? 'Sumulat ng <strong>T</strong> kung tama at <strong>M</strong> kung mali.' : 'Write <strong>T</strong> if the statement is correct and <strong>F</strong> if it is wrong.',
    'True or False (Write the Correct Answer)': isFil ? 'Isulat ang <strong>Tama</strong> kung tama. Kung mali, isulat ang wastong sagot.' : 'Write <strong>True</strong> if correct. If false, write the correct answer.',
    'Multiple Choice': isFil ? 'Piliin ang letra ng tamang sagot.' : 'Choose the letter of the correct answer.',
    'Matching Type': isFil ? 'Itugma ang Hanay A sa Hanay B.' : 'Match Column A with Column B.',
    'Word Bank': isFil ? 'Gamitin ang mga salita sa <strong>Word Bank</strong> para sagutan ang mga patlang.' : 'Use the words in the <strong>Word Bank</strong> to answer the blanks.',
    'Enumeration': isFil ? 'Isulat ang hinihinging listahan.' : 'Write the requested list.',
    'Essay / Extended Response': isFil ? 'Sagutin sa 1-2 pangungusap.' : 'Answer in 1-2 sentences.',
  };
  return map[type] || (isFil ? 'Sagutin nang tama.' : 'Answer correctly.');
}
function prelimRenderPartItemsHtml(p){
  const items = p.items||[];
  if(p.type === 'Multiple Choice'){
    return items.map((it,i)=>{
      const choices = (it.choices||[]).map((c,ci)=>`<div>${String.fromCharCode(65+ci)}. ${esc(c)}</div>`).join('');
      return `<div style="margin:4px 0;">_____ ${i+1}. ${esc(it.q)}<div style="margin-left:16px;display:grid;grid-template-columns:1fr 1fr;">${choices}</div></div>`;
    }).join('');
  }
  if(p.type === 'Matching Type'){
    const aLines = items.map((it,i)=>`<div>_____ ${i+1}. ${esc(it.q)}</div>`).join('');
    const order = p.matchOrder || items.map((_,i)=>i);
    const bLines = order.map((origIdx,slotIdx)=>`<div>${String.fromCharCode(65+slotIdx)}. ${esc(items[origIdx].columnB||items[origIdx].answer||'')}</div>`).join('');
    return `<div style="display:flex;gap:20px;"><div style="flex:1;"><strong>Column A</strong>${aLines}</div><div style="flex:1;"><strong>Column B</strong>${bLines}</div></div>`;
  }
  if(p.type === 'Word Bank'){
    const wb = (p.wordBank||[]).map(w=>`<strong>${esc(w)}</strong>`).join(' • ');
    const its = items.map((it,i)=>`<div style="margin:2px 0;">${i+1}. ${esc(it.q)}</div>`).join('');
    return `<div style="margin-bottom:6px;"><strong>Word Bank:</strong> ${wb}</div>${its}`;
  }
  if(p.type === 'Essay / Extended Response'){
    return items.map((it,i)=>`<div style="margin:4px 0;"><strong>${i+1}.</strong> ${esc(it.q)}<br>
      <div style="border-bottom:1px solid #ccc;margin:3px 0;height:18px;"></div>
      <div style="border-bottom:1px solid #ccc;margin:3px 0;height:18px;"></div></div>`).join('');
  }
  return items.map((it,i)=>`<div style="margin:2px 0;">_____ ${i+1}. ${esc(it.q)}</div>`).join('');
}
function prelimRenderPartAnswerHtml(p, isFil){
  const items = p.items||[];
  if(p.type === 'True or False'){
    return items.map((it,i)=>`<div><strong>${i+1}.</strong> ${(it.answer===true||it.answer==='true') ? (isFil?'T (Tama)':'T (True)') : (isFil?'M (Mali)':'F (False)')}</div>`).join('');
  }
  if(p.type === 'Multiple Choice'){
    return items.map((it,i)=>{
      const idx = (it.choices||[]).findIndex(c=>String(c).trim().toLowerCase()===String(it.answer||'').trim().toLowerCase());
      const letter = idx>=0 ? String.fromCharCode(65+idx) : '';
      return `<div><strong>${i+1}.</strong> ${letter}${letter?'. ':''}${esc(it.answer||'')}</div>`;
    }).join('');
  }
  if(p.type === 'Matching Type'){
    return items.map((it,i)=>{
      const letter = (p.matchLetterMap && p.matchLetterMap[i]) || '';
      return `<div><strong>${i+1}.</strong> ${letter}${letter?'. ':''}${esc(it.answer||it.columnB||'')}</div>`;
    }).join('');
  }
  if(p.type === 'Essay / Extended Response'){
    return `<em style="font-weight:400;">(Open-ended — check model answers in the downloaded Word file)</em>`;
  }
  return items.map((it,i)=>`<div><strong>${i+1}.</strong> ${esc(String(it.answer!==undefined&&it.answer!==null?it.answer:'—'))}</div>`).join('');
}

/* ── Preview renderer ── */
function prelimRenderPreview(){
  if(!prelimResult) return;
  const { parts, subject, grade, quarter, isFil } = prelimResult;
  const partLabels = ['I','II','III'];

  let bodyHtml = `
    <div style="text-align:center;font-weight:900;font-size:14px;">UPPER KLINAN SDA SCHOOL INC</div>
    <div style="text-align:center;font-size:11px;">Purok Mabinuligon, Upper Klinan, Polomolok, South Cotabato</div>
    <div style="text-align:center;font-size:11px;margin-bottom:6px;">School ID: 409417 &nbsp;•&nbsp; "Where Children Enjoy Holistic Learning"</div>
    <div style="text-align:center;font-weight:700;">${esc(quarter)} Quarter Prelim Exam &nbsp;|&nbsp; SY 2025-2026</div>
    <div style="text-align:center;font-weight:700;margin-bottom:8px;">${esc(subject)}</div>
    <div style="margin-bottom:8px;">Name: ___________________________________ &nbsp; Date: _________ &nbsp; Score: _________</div>
  `;
  let akHtml = '';

  (parts||[]).forEach((p, idx) => {
    const label = (isFil ? 'Bahagi ' : 'Part ') + (partLabels[idx]||(idx+1)) + '. ' + p.type;
    bodyHtml += `
    <hr style="margin:8px 0;">
    <div style="font-weight:700;margin:8px 0;">${label} (${(p.items||[]).length} pts)</div>
    <div style="font-style:italic;font-size:11px;margin-bottom:6px;">Story: <em>${esc(p.story||'')}</em><br>${prelimPreviewInstruction(p.type, isFil)}</div>
    ${prelimRenderPartItemsHtml(p)}`;
    akHtml += `
    <div style="font-weight:700;color:#E65100;margin:6px 0 3px;">${label}:</div>
    <div style="columns:2;column-gap:20px;margin-bottom:10px;">${prelimRenderPartAnswerHtml(p, isFil)}</div>`;
  });

  document.getElementById('prelimPreviewBody').innerHTML = bodyHtml;
  document.getElementById('prelimPreview').style.display = 'block';

  const akBody = document.getElementById('prelimAnsKeyBody');
  if(akBody) akBody.innerHTML = akHtml;
  /* Reset toggle button */
  const akWrap = document.getElementById('prelimAnsKeyWrap');
  const akBtn  = document.getElementById('prelimAnsKeyToggle');
  if(akWrap){ akWrap.style.display = 'none'; }
  if(akBtn) { akBtn.textContent = '👁 Show Answer Key'; }
}

/* ── Toggle prelim answer key ── */
function prelimToggleAnsKey(){
  const wrap = document.getElementById('prelimAnsKeyWrap');
  const btn  = document.getElementById('prelimAnsKeyToggle');
  if(!wrap) return;
  const show = wrap.style.display === 'none';
  wrap.style.display = show ? 'block' : 'none';
  btn.textContent    = show ? '🙈 Hide Answer Key' : '👁 Show Answer Key';
}

/* ── Docx instruction text per test type (plain text, no HTML tags) ── */
function prelimDocInstruction(type, isFil){
  const map = {
    'True or False': isFil ? 'Sumulat ng T kung tama at M kung mali.' : 'Write T if the statement is correct and F if it is wrong.',
    'True or False (Write the Correct Answer)': isFil ? 'Isulat ang Tama kung tama. Kung mali, isulat ang wastong sagot.' : 'Write True if correct. If false, write the correct answer.',
    'Multiple Choice': isFil ? 'Piliin ang letra ng tamang sagot.' : 'Choose the letter of the correct answer.',
    'Matching Type': isFil ? 'Itugma ang Hanay A sa Hanay B.' : 'Match Column A with Column B.',
    'Word Bank': isFil ? 'Gamitin ang mga salita sa Word Bank para sagutan ang mga patlang. Isulat ang tamang salita sa patlang.' : 'Use the words in the Word Bank to answer the blanks. Write the correct word on the line.',
    'Enumeration': isFil ? 'Isulat ang hinihinging listahan.' : 'Write the requested list.',
    'Essay / Extended Response': isFil ? 'Sagutin sa 1-2 pangungusap.' : 'Answer in 1-2 sentences.',
  };
  return map[type] || (isFil ? 'Sagutin nang tama.' : 'Answer correctly.');
}

/* ── DOCX Download ──
   Rewritten to build the file the SAME reliable way every other export in
   this app does (Lesson Plan, Summative, TOS, Final Exam): hand-written
   WordprocessingML XML wrapped in a Blob, no external library required.
   Now generalized to loop over whichever test types were picked for
   Part I/II/III (same options as Summative), instead of a fixed
   True-or-False / Word-Bank / Essay layout. ── */
async function prelimDownload(){
  if(!prelimResult){ toast('Generate the exam first.','te'); return; }

  try {

  const { parts: partsRaw, subject, grade, quarter, isFil } = prelimResult;
  const parts = (partsRaw || []).map(p => ({ type: p.type, story: p.story||'', items: p.items||[], wordBank: p.wordBank||[] }));

  const x = s => String(s || '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&apos;');

  const para = (text, opts = {}) => {
    const { bold = false, italic = false, color = '', center = false, sz = 22 } = opts;
    return `<w:p><w:pPr>${center ? '<w:jc w:val="center"/>' : ''}</w:pPr>
      <w:r><w:rPr>${bold ? '<w:b/>' : ''}${italic ? '<w:i/>' : ''}${color ? `<w:color w:val="${color}"/>` : ''}
      <w:sz w:val="${sz}"/><w:szCs w:val="${sz}"/><w:rFonts w:val="Times New Roman"/></w:rPr>
      <w:t xml:space="preserve">${x(text)}</w:t></w:r></w:p>`;
  };

  // Two-run paragraph (label in bold + value in italics), used for the "Story:" lines.
  const paraLabelValue = (label, value, opts = {}) => {
    const { sz = 22 } = opts;
    return `<w:p><w:pPr></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="${sz}"/><w:szCs w:val="${sz}"/><w:rFonts w:val="Times New Roman"/></w:rPr>
      <w:t xml:space="preserve">${x(label)}</w:t></w:r>
      <w:r><w:rPr><w:i/><w:sz w:val="${sz}"/><w:szCs w:val="${sz}"/><w:rFonts w:val="Times New Roman"/></w:rPr>
      <w:t xml:space="preserve">${x(value)}</w:t></w:r></w:p>`;
  };

  const rule = () => para('— — — — — — — — — — — — — — — — — — — — — — — — — — — —', { center: true, color: 'AAAAAA', sz: 16 });

  const blankLine = () => para('_'.repeat(90), { sz: 20 });

  const gradeLabel = grade || '';
  const partLabels = ['I','II','III'];

  const buildItemsXml = p => {
    const items = p.items || [];
    if(p.type === 'Multiple Choice'){
      return items.map((it,i) => {
        let block = para(`_____  ${i+1}. ${it.q}`, { sz: 22 });
        (it.choices||[]).forEach((c,ci) => { block += para(`        ${String.fromCharCode(65+ci)}. ${c}`, { sz: 22 }); });
        return block;
      }).join('');
    }
    if(p.type === 'Matching Type'){
      let block = para(isFil ? 'Hanay A' : 'Column A', { bold: true, sz: 22 });
      items.forEach((it,i) => { block += para(`_____  ${i+1}. ${it.q}`, { sz: 22 }); });
      block += para(isFil ? 'Hanay B' : 'Column B', { bold: true, sz: 22 });
      const order = p.matchOrder || items.map((_,i)=>i);
      order.forEach((origIdx,slotIdx) => {
        const bText = items[origIdx].columnB || items[origIdx].answer || '';
        block += para(`   ${String.fromCharCode(65+slotIdx)}. ${bText}`, { sz: 22 });
      });
      return block;
    }
    if(p.type === 'Word Bank'){
      let block = para(isFil ? 'Listahan ng Salita:' : 'Word Bank:', { bold: true, sz: 22 });
      block += para((p.wordBank || []).join('  •  '), { bold: true, sz: 22 });
      items.forEach((it,i) => { block += para(`${i+1}.  ${it.q}`, { sz: 22 }); });
      return block;
    }
    if(p.type === 'Essay / Extended Response'){
      return items.map((it,i) => para(`${i+1}. ${it.q}`, { sz: 22 }) + blankLine()+blankLine()+blankLine()+blankLine()).join('');
    }
    return items.map((it,i) => para(`_____  ${i+1}. ${it.q}`, { sz: 22 })).join('');
  };

  const buildAnswerXml = p => {
    const items = p.items || [];
    if(p.type === 'True or False'){
      return items.map((it,i) => para(`${i+1}. ${(it.answer===true||it.answer==='true') ? 'T' : 'F'}`, { sz: 20 })).join('');
    }
    if(p.type === 'Multiple Choice'){
      return items.map((it,i) => {
        const idx = (it.choices||[]).findIndex(c => String(c).trim().toLowerCase() === String(it.answer||'').trim().toLowerCase());
        const letter = idx>=0 ? String.fromCharCode(65+idx) : '';
        return para(`${i+1}. ${letter}${letter?'. ':''}${it.answer||''}`, { sz: 20 });
      }).join('');
    }
    if(p.type === 'Essay / Extended Response'){
      return para(isFil ? '(Bukas na sagot — tingnan ang mga modelong sagot)' : '(Open-ended — check model answers manually)', { color: '888888', italic: true, sz: 20 });
    }
    if(p.type === 'Matching Type'){
      return items.map((it,i) => {
        const letter = (p.matchLetterMap && p.matchLetterMap[i]) || '';
        return para(`${i+1}. ${letter}${letter?'. ':''}${it.answer||it.columnB||''}`, { sz: 20 });
      }).join('');
    }
    return items.map((it,i) => para(`${i+1}. ${it.answer!==undefined&&it.answer!==null ? it.answer : ''}`, { sz: 20 })).join('');
  };

  let bodyXml = '';
  let akXml = '';
  parts.forEach((p, idx) => {
    const label = (isFil ? 'Bahagi ' : 'Part ') + (partLabels[idx]||(idx+1)) + '. ' + p.type;
    bodyXml += `
  ${para(`${label} (${(p.items||[]).length} pts)`, { bold: true, sz: 24 })}
  ${paraLabelValue('Story: ', p.story || '')}
  ${para('👉 ' + prelimDocInstruction(p.type, isFil), { sz: 22 })}
  <w:p/>
  ${buildItemsXml(p)}
  ${rule()}`;
    akXml += `
  ${para(`${label}:`, { bold: true, sz: 22 })}
  ${buildAnswerXml(p)}
  <w:p/>`;
  });

  const xml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?mso-application progid="Word.Document"?>
<w:wordDocument xmlns:w="http://schemas.microsoft.com/office/word/2003/wordml"
  xmlns:wx="http://schemas.microsoft.com/office/word/2003/auxHint"
  w:macrosPresent="no" w:embeddedObjPresent="no" w:ocxPresent="no">
<w:body>
  <w:sectPr>
    <w:pgSz w:w="12240" w:h="15840" w:orient="portrait"/>
    <w:pgMar w:top="1080" w:right="1080" w:bottom="1080" w:left="1080"/>
  </w:sectPr>

  ${para('UPPER KLINAN SDA SCHOOL INC', { bold: true, center: true, sz: 28 })}
  ${para('Purok Mabinuligon, Upper Klinan, Polomolok, South Cotabato', { center: true, sz: 20 })}
  ${para('School ID: 409417', { center: true, sz: 20 })}
  ${para('"Where Children Enjoy Holistic Learning"', { center: true, sz: 20, italic: true })}
  ${para(`${quarter} Quarter`, { bold: true, center: true, sz: 24 })}
  ${para('Prelim Exam', { bold: true, center: true, sz: 26 })}
  ${para('SY 2025-2026', { bold: true, center: true, sz: 22 })}
  ${para(`${subject}${gradeLabel ? ' — ' + gradeLabel : ''}`, { bold: true, center: true, sz: 26 })}
  <w:p/>

  ${para('Name: _______________________________________     Date: __________     Score: __________', { sz: 22 })}
  ${rule()}
  ${bodyXml}

  ${para(isFil ? 'SUSI SA PAGWAWASTO (Answer Key)' : 'ANSWER KEY', { bold: true, center: true, color: '2E7D32', sz: 24 })}
  <w:p/>
  ${akXml}
</w:body>
</w:wordDocument>`;

  const blob = new Blob([xml], { type: 'application/msword' });
  const safeSubject = (subject || 'Subject').replace(/[^\w\s-]/g, '').replace(/\s+/g, '_').slice(0, 40);
  const safeQuarter = (quarter || '').replace(/[^\w\s-]/g, '').replace(/\s+/g, '');
  const fname = `${safeSubject}_${safeQuarter}_Prelim_Exam.doc`;
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fname;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1500);
  toast('✅ Prelim Exam downloaded as Word (.doc)!', 'ts');

  } catch (e) {
    console.error(e);
    toast('❌ Download error: ' + (e && e.message ? e.message : e), 'te');
  }
}
/* ── END PRELIM EXAM ── */
